### ISSUE TITLE
Set up Jenkins

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#1]
Set up Jenkins for Terrier.
As stated in Peloton PR #1458, re-purpose the MemSQL machines. These can be the starting point for systems used for Terrier. Machines currently used for Peloton can be migrated over to Terrier as activity increases.

Ubuntu 18.04 only.
- C++ 17 (= gcc7, clang 6)
- LLVM 6.0
- cmake 3.2

At the moment the repo has just a skeleton setup in it. Matt Butrovich has been setting up the Cmake components.

There are no code review requirements, so feel free to commit Jenkins file and update as needed.

**Comment by tli2** [comment]
I think this is done pending some bug-fixes?
