### ISSUE TITLE
Merge SQL Functions from May 2020 Hack-a-Thon

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#1001]
There are several PRs in my personal fork from our May2020 hack-a-thon. These are new SQL functions written by the students last semester:

https://github.com/apavlo/terrier/pulls

We need to merge them together into a clean branch and then submit them as a single PR to the master repo. I have reviewed some of the students code but not all of it.

We will also need to port their modifications to [FunctionsTest.java](https://github.com/cmu-db/terrier/blob/master/script/testing/junit/src/FunctionsTest.java) to use @dniu16's new SQLite trace file format when he gets that merged.

I will try to go through and approve the PRs. This would be a good beginner project for somebody to help us in dealing with the conflicts.

**Comment by wgy8283335** [comment]
@apavlo. I'd like to take this task. As we need to merge them together into a clean branch, maybe we should create a new branch based on master branch in the cmu-db/terrier project. I do not have the rights to create it, could you help me?
![image](https://user-images.githubusercontent.com/22066046/88353085-c6a56680-cd8e-11ea-8eab-5cf0fdd7c9aa.png)

**Comment by wgy8283335** [comment]
@apavlo Dear Professor Pavlo. Do I need to create a new branch based on master branch in the "cmu-db/terrier" repository? Or I just review those commits in the "apavlo/terrier" repository?

**Comment by apavlo** [comment]
@wgy8283335 Here is a rough outline of the steps on how to proceed with this task:

1. Fork apavlo/terrier:master into your own branch. It already contains some merged functions:
    a. https://github.com/apavlo/terrier/pull/7
    b. https://github.com/apavlo/terrier/pull/5
    c. https://github.com/apavlo/terrier/pull/4
2. Update your new branch to pull in the changes from cmu-db/terrier:master
3. Manually merge in the remaining pull requests from apavlo/terrier into your new branch: https://github.com/apavlo/terrier/pulls

For this last step, there will be many conflicts in the files because the everyone was updating the same ones. But these should be easy to manually resolve.

You'll also want to move the test queries out of `FunctionsTest.java` and add them to [functions.sql](https://github.com/cmu-db/terrier/blob/master/script/testing/junit/traces/functions.sql). We removed most of the old Java test files.

**Comment by apavlo** [comment]
@wgy8283335 After discussing this internally, we think that it would be better to do this in stages with separate PRs, rather than one giant PR. I would start with reviving my current master branch and submit a PR after updating that.

We can then work through the remaining PRs one-by-one. Let me know if this makes sense.

**Comment by wgy8283335** [comment]
@apavlo Dear Professor Pavlo. I think this is a good idea. Because I have checked the PRs, they have many files totally. Merge PRs one-by-one is better.

**Comment by wgy8283335** [comment]
@apavlo Dear Professor Pavlo, have you revived your master branch? Or I could do some other works before your master has been revived.  Do you have any optimizer related issues or works that need to be contributed?

**Comment by jkosh44** [comment]
@apavlo All these functions have now been merged except for MD5. It's up to you whether or not you want to leave this open or track with a separate issue. Also you can close all the PRs on your fork.
