### ISSUE TITLE
Consider using -Og instead of -O0

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/terrier#1007]
> Optimize debugging experience. -Og should be the optimization level of choice for the standard edit-compile-debug cycle, offering a reasonable level of optimization while maintaining fast compilation and a good debugging experience. It is a better choice than -O0 for producing debuggable code because some compiler passes that collect debug information are disabled at -O0. - GCC [0]

> -Og Like -O1. In future versions, this option might disable different optimizations in order to improve debuggability. - Clang [1]

Did we consider using that? [2]

[0] https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
[1] https://clang.llvm.org/docs/CommandGuide/clang.html
[2] https://github.com/cmu-db/terrier/blob/master/cmake_modules/SetupCxxFlags.cmake#L41

**Comment by mbutrovich** [comment]
No objection. Seems like an easy change.

**Comment by lmwnshn** [comment]
Objection. Debugging experience turned to crap when trying to step around in `void PlanGenerator::Visit(const InnerNLJoin *op)` calling out to `parser::ExpressionUtil::EvaluateExpression`. I vote we don't use this.

**Comment by lmwnshn** [comment]
We're not going to do this.
