### ISSUE TITLE
Add support for running multiple OLTP-Benchmark without loading data every time

### ISSUE THREAD

**Issue by skyfishjy** [cmu-db/terrier#1011]
For multiple experiments that running the same benchmark but with different workloads, one could pass a list as a command-line arguments (to loop over _terminals_) to the `run_oltpbench.py`:

<pre>run_oltpbench.py tpcc 45,43,4,4,4 --loader-threads=4 --client-time=60 --terminals=1,2,4,8,16</pre>

The run_oltpbench.py script would first create a and populate a database that can be reused, and then run experiments with different workloads on it. 

Then we could reduce the data loading time when we run some scalability testing(e.g. [nightly job on Jenkins](https://github.com/cmu-db/terrier/blob/cdaefb5611e52be9c01aeef451614d7ccf45b940/Jenkinsfile-nightly#L58))

**Comment by apavlo** [comment]
Why was this closed?
