### ISSUE TITLE
ExportTableTest::CheckContent Does Not Provide Useful Feedback

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#1013]
The `export_table_test` fails randomly on Jenkins. Thanks to @crd477, we can actually see the debug output now for the failed test:

http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-938/54/tests/

This says that we are failing `ExportTableTest::CheckContent`. This function is responsible for reading the data back in from the exported file to see whether it matches what we expect:

https://github.com/cmu-db/terrier/blob/master/test/storage/export_table_test.cpp#L268

The problem, however, is that the test only checks whether `CheckContent` returns true or false. There is no useful feedback to say which of the checks inside of `CheckContent` is failing.

We need to refactor this function so that the asserts are inside of `CheckContent` rather than just returning false for the entire function invocation. This will help us begin to understand why this test case is failing randomly.

**Comment by YuzeLiao** [comment]
Happened to see this issue -- sorry for not providing enough debuggability :(. If you don't mind it I'll refactor the code and try to reproduce the failure to see what went wrong.

**Comment by apavlo** [comment]
@YuzeLiao That would be great! Just let us know if you don't have the time for it so that I can assign it to another student.

**Comment by apavlo** [comment]
Fixed in #1019
