### ISSUE TITLE
Cleanup week!

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/terrier#105]
It's been a month of rapid engineering by a very small team, and now we need a few days to reflect on what we've accomplished and get the codebase ready for a lot more people to work on it. To that end, we're going to complete the following next week:

- [x] Arrow's codebase assumed .cc files. A quick search shows that we should change cpplint and run_clang_format. Previously, it was only doing that for .h files. We can also try to make cpplint.py work for Python 3. We’ll do this at the end of the week to avoid merge conflicts on other PRs. (PR is open #117, ready to go whenever we are).
- [x] Revisit every TODO in the codebase. We sprinkled these liberally through the codebase when we didn't know the answer to questions, and some are now irrelevant.
- [x] Revisit code documentation to make sure it's still correct. APIs, behavior, and assumptions might have changed since first written. Some hidden assumptions will also need to be made explicit and clearly documented. Suggest turning on -Wdocumentation locally on Clang for extra help finding issues.
- [x] Add debug logging statements where appropriate.
- [x] Break some class definitions into their own files. Closely related classes were often written in the same headers since that was easier for engineering, but we should make the files more accessible now.
- [x] Make sure definitions are in .cpp files rather than .h files when appropriate. Again, this was easier for engineering but we want to make sure we're following our own guidelines.
- [ ] Revisit and expand the wiki documentation. Design decisions in the storage and CC layers have been in flux for a month, but we've more or less settled on our design and should document them (issue #46). Some infrastructure stuff has also changed (lint target, CI, etc.) and we want to make sure that's current.
- [ ] Get our Continuous Integration (both Travis and Jenkins) running the checks that we want. This mostly involves shifting work to Jenkins and getting the dependency in place for Jenkins to trigger after Travis.
- [x] Make unit test and benchmark parameters consistent, in particular number of threads, and put these in a common harness.
- [x] Magic numbers, names, and other readability improvements.
- [ ] Get a benchmark machine set up to collect nightly numbers so we can spot regressions.
- [x] Revisit the memory alignment and padding stuff in our allocators. It's possible that we could be more efficient using [posix_memalign](http://man7.org/linux/man-pages/man3/posix_memalign.3.html) where appropriate. Arrow's [allocator](https://github.com/apache/arrow/blob/master/cpp/src/arrow/allocator.h) and [memory](https://github.com/apache/arrow/blob/master/cpp/src/arrow/memory_pool.h) [pool](https://github.com/apache/arrow/blob/master/cpp/src/arrow/memory_pool.cc) could prove inspirational.
- [x] Reference Coveralls for completely uncovered files and consider removing them from the repo. (Done. Only file not used is concurrent_map.h but we can keep that around. -Matt)

**Comment by mbutrovich** [comment]
Close enough. Mostly just chilling away at CI stuff which we have separate issues to track.
