### ISSUE TITLE
Enhance ObjectPool for runtime changes and pre-allocation

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#109]
The object pool implementation now is basic and simple keeps a queue around for reuse up to a certain limit. We want 2 things:

- The reuse limit should be tunable. We might want to increase the reuse limit when memory usage goes up, and free memory when it goes back down.
- When the queue  is empty and we are calling malloc, we only do it one at a time for now. It might make sense to put several objects onto the queue at the same time (maybe contiguous in memory?).

**Comment by yangjuns** [comment]
If we want to do bulk malloc when the queue is empty, how much space should be allocated (how many objects should be filled in the reuse queue)?  Half-full?

**Comment by tli2** [comment]
make it tunable as well, I guess.

Also, just FYI since we are going to clean up the code base next week, this will either be ready and go in before early next week (Tue? Wed? Not sure when we will start clean up week), or after the refactors.

**Comment by tli2** [comment]
It might be worthwhile investigating what Apache Arrow does for this thing as well. Comment from #105 talks about this. Replicated below:

Revisit the memory alignment and padding stuff in our allocators. It's possible that we could be more efficient using [posix_memalign](http://man7.org/linux/man-pages/man3/posix_memalign.3.html) where appropriate. Arrow's [allocator](https://github.com/apache/arrow/blob/master/cpp/src/arrow/allocator.h) and [memory](https://github.com/apache/arrow/blob/master/cpp/src/arrow/memory_pool.h) [pool](https://github.com/apache/arrow/blob/master/cpp/src/arrow/memory_pool.cc) could prove inspirational.

**Comment by tli2** [comment]
Per discussion on the meeting we will also need to design around the object pool's behavior when there are no objects to hand out.

**Comment by tli2** [comment]
fixed by #127
