### ISSUE TITLE
What is the meaning of TPL?

### ISSUE THREAD

**Issue by wgy8283335** [cmu-db/terrier#1095]
What is the meaning of the word 'TPL ' that appeared in the files in the execution directory? 
Such as TPL bytecode, TPL subsystems, TPL AST CallExpr.
I'd like to understand the ‘TPL’ related knowledge。

**Comment by apavlo** [comment]
Terrier Programming Language

**Comment by apavlo** [comment]
@wgy8283335 See this write-up of MemSQL's internal DSL. TPL is similar to this: http://highscalability.com/blog/2016/9/7/code-generation-the-inner-sanctum-of-database-performance.html

**Comment by wgy8283335** [comment]
@apavlo Thank you very much.

**Comment by Xavier1994** [comment]
hi, @apavlo TPL is an open source PL, or you created it? I do not find any related tutorial about it
