### ISSUE TITLE
tuple_access_strategy_test times out on Ubuntu 18.04 Docker

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/terrier#11]
(Docker setup guide available on our [wiki](https://github.com/cmu-db/terrier/wiki/Docker))

When running make test on both my local machine and Travis, the Ubuntu 18.04 Docker image gets stuck on tuple_access_strategy_test. I have let it run locally for over an hour.

tuple_access_strategy_test however completes in ~70 seconds on OSX.

**Comment by mbutrovich** [comment]
Runs extremely slowly on my 18.04 box as well. Something is fishy in Linux land.

**Comment by lmwnshn** [comment]
For future reference: the issue was that C++ doesn't have cross-platform random distributions.
e.g. on first run, Mac ran 2 inserts while Ubuntu ran 700k inserts.

We fixed this by capping the amount of randomly generated work.
