### ISSUE TITLE
Is ExecutionMode::Interpret the only one mode which is used in SQL execution?

### ISSUE THREAD

**Issue by wgy8283335** [cmu-db/terrier#1115]
I've read codes in the execution package.` ExecutableQuery::Run()` only execute in Interpret mode, as it called by traffic_cop
`traffice_cop.exec_query->Run(common::ManagedPointer(exec_ctx), execution::vm::ExecutionMode::Interpret)`.
`tpl_module_->GetFunction()` support Adaptive, Interpret, Compiled. But it called in Interpret mode by executable_query.cpp. Other 2 types mode is called in tpl.cpp-CompileAndRun(). As:
```
module->GetFunction("main", vm::ExecutionMode::Adaptive, &main)
module->GetFunction("main", vm::ExecutionMode::Compiled, &main)
```
But tpl.cpp-CompileAndRun() seems to have not been used in the SQL execution of the terrier database.
So will the Adaptive and Compiled mode, will be used in the SQL execution in the future? And what is the purpose of tpl.cpp?

**Comment by mbutrovich** [comment]
You can change execution mode with the setting introduced in #1057. tpl.cpp is used to invoke standalone .tpl files.
