### ISSUE TITLE
Design adjustments from Peloton

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#114]
There are a number of things discovered during the work on codegen support for index scans, that have not been merged into Peloton. These will need to be addressed correctly in Terrier. This issue describes the issues, for new designs to address or, if code is ported from Peloton, to correct the issues in the new context. 

**Contents**
1. Text vs. binary marshaling for network communication. 
2. Plan objects contents should not store execution state
3. Run time query state
4. PerformBinding issues

**Descriptions**
---
**Text vs. binary marshaling.**
The Postgres protocol JDBC driver performs some optimizations at run time. These are not immediately obvious from using JDBC and must be handled correctly in the implementation.

See [https://jdbc.postgresql.org/documentation/head/server-prepare.html](url)
To summarize the information:

- The driver will use server side prepared statements after a configurable number of calls to the prepared statement. The transition is controlled by the prepareThreshold connection property. The default value is 5. 
- When the threshold is crossed, the driver switches from text marshaling of responses to binary marshal of responses. 

There should be a single instance of the marshaling code, in the network communication layer. In Peloton, it is down in the executor layer, with a second instance being required in the codegen execution pathway.

Further, this behavior requires that unit tests exercise both text and binary marshaling.

---
**Plan objects**
Plan instances should contain only invariant information. No per invocation state should be stored in the plan. For example:
- INSERT into tbl VALUES (1); The value inserted is a constant and may be stored in the plan.

- INSERT into tbl VALUES (?); This form is used by prepared statements. The plan is re-used with differing values, which should not be stored in the plan instance.

---
**Run time query state**
Peloton's ExecutorContext stores any invocation specific state. 

To summarize this and the prior item:
- Invariant information can be part of the plan object
- Any information that is specific to an execution instance of a query, must be in the ExecutorContext.
- Any code imported from Peloton may need review and fixes for this issue.

---
**PerformBinding**
PerformBinding is called on the plan tree, prior to execution of the plan. Amongst other things, this sets up information required for lower level plan nodes to communicate their output to higher plan nodes. For example, in the codegen path in Peloton, ais (i.e. attribute names etc), need to be initialized. These identify the columns to be passed. 

The process of "PerformBinding" in Peloton still has bugs when using codegen when dealing with server side prepared statements and when dealing with non-trivial plan trees.  Perform binding suffers from:
- Appending to initialized state, when the state has already been set once. This results in failure. See Peloton issue: [https://github.com/cmu-db/peloton/issues/1394](url)
- Omitting initialization in non-trivial plan trees. 

In summary:
- The PerformBinding calls need review, if ported
- Clean separation between invariant state and run time state, as noted in the earlier points, should be implemented and would be part of the solution.

**Comment by mbutrovich** [comment]
I think all of these have been addressed.
