### ISSUE TITLE
Intermittent Jenkins failures

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#134]
Been seeing this off and on since Jenkins was enabled:
```
[terrier_PR-117-OQYACMCYLGTWIB5WRVRHBKS7GCQCONHDWA3HAAJLOOZ4ZLYOLUFQ] Running shell script
+ docker inspect -f . ubuntu:bionic
.
Failed to run image 'ubuntu:bionic'. Error: docker: Error response from daemon: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused".
```
Here's a recent PR with this error on one of the machines:
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-117/8/pipeline/9/

**Comment by mbutrovich** [comment]
The most recent master build failed for the same reason:
http://jenkins.db.cs.cmu.edu:8080/job/terrier/job/master/

**Comment by crd477** [comment]
I work for the butler!  I thought it was supposed to be the other way around!  If I end up joining your group for the event Andy suggested, I'm going to print out a stack of papers with the Jenkins logo on it.

All kidding aside, I'll look into it.

**Comment by crd477** [comment]
Actually, this turned out to be pretty simple.  `dockerd` on one of the Jenkins workers lost its mind and there were a bunch of old, stray containers leftover.  I cleaned them up and it should be good now.

**Comment by mbutrovich** [comment]
Thanks for the quick response and help @crd477!
