### ISSUE TITLE
TupleId

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#145]
Currently the first column of a DataTable is an 8-byte attr that is used as a pointer to the next version in the delta chain, while its null bit is used to represent "presence". Basically, that's what the DataTable uses to find empty slots.

We want to add a feature that the second column is an 8-byte attr that is used as a TupleId (unique, suitable for use as a primary key) while its null bit is used to represent logically deleted.

**Comment by mbutrovich** [comment]
Today's discussion left us with:
- TupleId is not needed for logging/recovery, so we will not make this a Storage level concept
- Second column can probably be set to 8 bytes for now just to leave room for TupleId from the execution layer. If we decide we ultimately don't need TupleIds for anything, we can not implement them.
