### ISSUE TITLE
Bringing in Index

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#147]
We want to start bringing in the bw_tree as our index. This will entail:
- [x] adding bwtree.h/.cpp to the third_party folder
- [ ] modify the wrapper bwtree_index.h to not inherit from index.h anymore, and any other adjustments we need to make it work with Terrier
- [ ] discuss any other dependencies you find before bringing them in

**Comment by mbutrovich** [comment]
We want to bring it in from Peloton, since I think that's newer (has bug fixes) than Ziqi's own repository.

**Comment by apavlo** [comment]
I think all of the fixes from @wangziqi2013's repo is in the Peloton master branch now.
