### ISSUE TITLE
Read-only Transactions don't need commit timestamps

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#163]
They don't really exist. We can easily tell read-only transactions in the commit method by checking if its undo buffer is empty. Essentially we get to skip most of the commit and logging logic, just remove said transaction from the list of running transactions and hand it to the garbage collector, returning its begin timestamp as commit timestamp. (They still need a timestamp if we are running Serializable)

Support the theoretical speedup with benchmark numbers.

**Comment by tli2** [comment]
Matt suggests that this is not a performance gain necessarily. Can always leave for later.

**Comment by tli2** [comment]
Extra item: They don't need a commit record written to disk necessarily either.

**Comment by mbutrovich** [comment]
#209 represents the logging optimization in the comment, and the commit logic has already been changed in #221.

Timestamps are still in theory unnecessary, but we'll address that as we hit scaling issues across threads.
