### ISSUE TITLE
Write-ahead-log code path can be optimized for read-only transactions

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#209]
As it stands, read-only transactions also generate commit records. Since we use commit records to embed callbacks for group-commit, we cannot remove them. However, there is no reason for them to be actually serialized and written out to disk.

It is possible to structure commit records to somehow convey that a transactions is read-only (commit_time == begin_time, things like that), and check for this in the `LogManager`. We can then process the callback only and not write the record out to disk.

**Comment by mbutrovich** [comment]
commit_time == begin_time would need some modification in the GC to work correctly.

**Comment by tli2** [comment]
This is only for within the redo-record.
Or add a bit flag somewhere. Not too big of a problem.
