### ISSUE TITLE
tmpsfs ramdisk on Jenkins benchmark machine

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#216]
We want a tmpfs ramdisk so we can add a WAL benchmark suite to the CI runs. I followed the guide on [this page](https://www.jamescoyle.net/how-to/943-create-a-ram-disk-in-linux) when I set one up on dev4. I believe this was all I did:

```
mkdir /mnt/ramdisk
mount -t tmpfs -o size=30g tmpfs /mnt/ramdisk
```

I'll give exact ramdisk size requirements in the next 24 hours after I experiment on dev4 tonight to balance between performance variance and runtime and log file size.

**Comment by crd477** [comment]
For the record, memory usage on the system that currently handles the benchmark step looks as follows when no builds are running:
```
[crd@h2.narwhal ~]$ free -g
              total        used        free      shared  buff/cache   available
Mem:            251           1         245           0           5         248
Swap:             2           0           2
```
So the world's your oyster...

**Comment by mbutrovich** [comment]
It's looking like 20GB will be safe based on the benchmark's behavior on dev4.

**Comment by pervazea** [comment]
Ramdisk created. 20g, also added to fstab.
