### ISSUE TITLE
Bump AppleClang/Xcode version to 10

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#247]
#246 requires the addition of ` -Wno-invalid-offsetof` to Clang compiler flags because the way we use `offsetof` in the BwTree is undefined behavior before C++17. We are currently using AppleClang/Xcode 9 on Travis and Jenkins as well as our [System Setup](https://github.com/cmu-db/terrier/wiki/System-Setup) wiki page. AppleClang/Xcode 10 brings better support for C++17, including no longer needing that flag.

I have a branch to handle the Travis changes [here](https://github.com/mbutrovich/terrier/tree/xcode10) which are pretty simple, but will need to talk to @crd477 next week (or after Thanksgiving) about updating the Jenkins Docker images. After those are in place and a PR is merged, we should update the Wiki as well.

**Comment by crd477** [comment]
I'm working on this now.  It shouldn't take too long.

**Comment by mbutrovich** [comment]
Gonna leave this open until the Travis stuff gets merged in.
