### ISSUE TITLE
Enhance parser tests

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#250]
For Weichen Ke

First, some general hints about getting set up for development, then more specifics about the task, which is to make the parser tests better.

Development environment. You'll find useful information in the Terrier wiki pages. When something is not clear, feel free to ask via email or on the CMU group's Slack channel(s). Recommended that you set up a system for development:
- Ubuntu 18.04 (VM is ok if you don't have this natively). Mac OSX is usable too I think.
- CLion is the recommended IDE. You can get a free license as a student. Eclipse if you prefer, but not as easy to configure and set up.
- Be able to compile terrier. Targets that you will need, include check-clang-tidy, check-format, check-lint and unittests. For the format targets, just compiling does the checks. For the unittests, run the target.

For the parser, we've been working from branch pgparser_neue, git repo: https://github.com/lmwnshn/terrier.git. In other words, it isn't integrated into the main repo yet. 

Tests are under directory:
test/parser. The test you'll want to focus on is parser_test.cpp.

For example, look at line 134, the OldAggTest. This test parses a few SELECT statements, but only checks if the parse completes. It does not check that the parse produced what was expected. As you look at other tests in the file, you'll find some that are like the above tests, no checking of results. Others do check results, but sometimes not checking all parts of the result. Review the tests and modify them to check the parse results.

Second part, is to review the SQL strings being fed into the parser. I expect you'll find that we do not cover all the possible SQL inputs. Add tests or variations to check SQL input cases that are missing or incomplete.

**Comment by mbutrovich** [comment]
I think the best order of operations when working with others' branches for the project:
1. Fork the repo from cmu-db/terrier
2. Clone your fork locally
3. Add any other users' remotes that you need to your local repo (i.e. git remote add, or use VCS > Git > Remotes in CLion

<img width="410" alt="git_remotes" src="https://user-images.githubusercontent.com/6855576/48972833-e0fad000-f000-11e8-93f2-293bd46b9f15.png">

4. Fetch and then checkout the remote branch that you want. You probably won't have push access to that users' repo unless they've made you a collaborator (or a reviewer for a PR on that branch). So just push back to your under a branch with the same name. Periodically just merge their changes from the remote into your branch.

**Comment by ParthS007** [comment]
Hello @pervazea, I want to work on this Issue. 
@DarkForte Are you still working on this?

@pervazea I am new to this Project and want to start contributing. If you can please provide the link to other beginner-friendly Issues, It would be of great help to me. 
Thanks :smiley:

**Comment by DarkForte** [comment]
Hi Parth, I am still working on it...

**Comment by ParthS007** [comment]
Thanks, @DarkForte for the quick reply.

Can you please help me to start contributing and provide the link of other open beginner-friendly Issues.
Do you have any community channel for this Project(If yes, can you please provide the link for the same)?

**Comment by DarkForte** [comment]
I have added some test contents. Shall I send the PR to https://github.com/lmwnshn/terrier.git?

**Comment by lmwnshn** [comment]
@DarkForte Open the PR against the main repo (this).

**Comment by lmwnshn** [comment]
More tests are always welcome, but we got #276 #292 #296 which is pretty good. We're testing at least as much as Peloton, except now we also verify the parse result.
