### ISSUE TITLE
Finding correct llvm version

### ISSUE THREAD

**Issue by DarkForte** [cmu-db/terrier#251]
I met a problem when building. I ran `installation/packages.sh`, and indeed installed `llvm-6.0`, but the `cmake` script insists that the version of `llvm` is `3.9`. It seems that I have llvm 3.9 on my machine too. How can I tell `cmake` to find the correct `llvm`? Do I need to uninstall 3.9?

![image](https://user-images.githubusercontent.com/8542129/48973277-cda03280-f009-11e8-8e47-052519fcdea2.png)

Thanks!

**Comment by mbutrovich** [comment]
What happens if you define LLVM_DIR to point to 6.0?

**Comment by DarkForte** [comment]
Ah, I uninstalled 3.9 and it worked!
`sudo apt-get remove llvm-3.9` 
Perhaps someone else installed this for me and `cmake` found this one before finding 6.0. I'll close this.

Thanks!

**Comment by mbutrovich** [comment]
If you installed Peloton, 3.9 came from that. You can have both installed at the same time. On Ubuntu you set `LLVM_DIR=/usr/lib/llvm-6.0/cmake` to specify 6.0.
