### ISSUE TITLE
bwtree unit test fails

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#264]
Working on parser and plan nodes. Pulled from master yesterday and merged it into the branch on which Wan and I are working.

When running unit tests this morning, the bwtree test fails (run time 168.86 sec).

No other information at this time. Just ran once so far.

**Comment by tli2** [comment]
I think it reliably fails on dev4 as of master today

**Comment by yeshengm** [comment]
Here's a screenshot of the failed test case.

![screenshot from 2019-02-12 22-06-56](https://user-images.githubusercontent.com/12269969/52683983-a07d6500-2f12-11e9-9188-0ed6683b1046.png)

**Comment by mbutrovich** [comment]
What machine is this on: specifically how many threads? This has not reproduced on any machines I've tried, but can try dev4 since @tli2 says he saw failures there.

**Comment by yeshengm** [comment]
I'm testing on EC2 c5.9xlarge (36 cores).

**Comment by mbutrovich** [comment]
I can reproduce it in Terrier on dev4 which is just a port of @wangziqi2013's tests. I'm trying the original BwTree repo to see if it reproduces there too.

**Comment by mbutrovich** [comment]
Reproduced on @wangziqi2013's BwTree repo. I'll track him down for help. :)

[bwtree_test_failure.txt](https://github.com/cmu-db/terrier/files/2861256/bwtree_test_failure.txt)

**Comment by mbutrovich** [comment]
I think we're good here.
