### ISSUE TITLE
OIDs

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#265]
The note below outlines the proposed structure of OIDs, for comment and input. Once accepted, the summary should be written into the Wiki as a statement of how we've designed the OIDs.

Like the other types in Terrier, OIDs are strongly typed.
Each type of OID is allocated from its own OID value space.

There is a single, global OID value space for each of the types of OIDs.

1. Database OIDs (database_oid_t)
1. Namespace OIDs (namespace_oid_t)
1. Table OIDs (table_oid_t)
1. Column OIDs (column_oid_t)

Alternatives:

1. A single global database OID space. Within each database, there is
a single OID value space for all other types, i.e. tables, columns
etc. This provides:
     - Each database has a unique OID
     - within each database, tables, columns etc. are allocated an
       OID. A table and column will not ever have the same OID value.

       Table B in database A may have OID 1

       Table C in database D may also have OID 1
       Column E in table C may have OID 2. It cannot have OID 1.

2. A single global database OID space, with separate, local to each
database, OID value spaces for other types, i.e. tables, columns
etc. This provides:
     - Each database has a unique (global) OID
     - Within each database, each object type has a OID value that is
       distinct only within that object type. This gives:

       A table B in database A, may have OID 1
       A column in table B, may also have OID 1

**Comment by yangjuns** [comment]
The current implementation of #260 uses alternative 2.

**Comment by lmwnshn** [comment]
Though I think alternative 2 means storing more data in memory (sizeof(OID) * number of types * number of databases).

**Comment by yangjuns** [comment]
Based on today's discussion, we decided to go for alternative 1 because users can see oids but cannot distinguish a table_oid and a col_oid.

**Comment by yeshengm** [comment]
- `__ptr` in our `pg_class` implementation breaks the numbering with Postgres, needs some workaround to fix that. Otherwise all columns are shifted by 1.

**Comment by pervazea** [comment]
Looking at the code, what we have, does not appear to be option 1 either :-) If I read the code correctly, we have a single, global oid value space. So every oid, regardless of type, is unique.
