### ISSUE TITLE
Tuple and Value

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#267]
After discussions with @yangjuns  a few days ago and the meeting today, the need for translation code between Values and the storage layer is here. @yangjuns need to drop SQL values into the SqlTable, and right now the code to go between Values and ProjectedRow fields as the buffer between execution and storage layer doesn't exist.

Right now we're proposing Tuple is just access methods that wraps around a reinterpreted ProjectedRow, exposing fields as Values to avoid duplicate materialization. I'll go forward with this model for the time being.

**Comment by lmwnshn** [comment]
Closed after talking briefly to @mbutrovich. This is the TransientValue and ValuePeeker stuff.
