### ISSUE TITLE
The libz-dev dependency should be zlib1g-dev

### ISSUE THREAD

**Issue by manifoldQAQ** [cmu-db/terrier#279]
The dependency `libz-dev` actually no longer exists in Ubuntu packages. The alternative should be `zlib1g-dev` as in [Ubuntu Packages Index](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=zlib1g-dev&searchon=names). Can I send a PR on it?

**Comment by mbutrovich** [comment]
Absolutely, thank you!

**Comment by manifoldQAQ** [comment]
I'm actually using 18.04. If I send a PR, then I think the CI process will report an error if it breaks?

**Comment by mbutrovich** [comment]
CI should catch it if it breaks anything on 18.04.
