### ISSUE TITLE
Memory Leak in Test Infrastructure

### ISSUE THREAD

**Issue by jrolli** [cmu-db/terrier#283]
There is a memory leak in `LargeTransaction::SimulateOltp` when the `bookkeeping` flag is set to `false` and `TransactionManager::RegisterWorker` returns a non-null pointer and expects a corresponding call to `TransactionManager::UnregisterWorker`.

Specifically, `SimulatOltp` calls `RegisterWorker` in line 119 and `UnregisterWorker` in line 163 (test/util/transaction_test_util.cpp).  However, when `bookkeeping` is set to false, the code short-circuit returns at line 152 without calling `UnregisterWorker`.  Currently, `test/storage/log_test.cpp` is the only test that reaches this code (WriteAheadLoggingTests.ReadOnlyTransactionsGenerateNoLogTest).

This bug is reproducible by running `make log_test` with ASAN enabled and modifications that return a pointer to an allocated object in `RegisterWorker` that is deallocated in `UnregisterWorker`.

**Comment by mbutrovich** [comment]
Just to be clear since I was confused by the code being referenced, this only affects the `15721-s19-project1` branch.

**Comment by jrolli** [comment]
Looking at the commit logs, the bug appears to be present in master but untriggered because RegisterWorker is unimplemented.

**Comment by jrolli** [comment]
Correction it is just in the 15721 branch.
