### ISSUE TITLE
GC test failure on 32-core on high abort

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#287]
C++ exception of vector index access out of bounds reported by student. Because the access was UINT64_MAX into a 0-size array, overflow is the likely cause.

**Comment by yeshengm** [comment]
Shouldn't this change get merged into the project branch? Also the BwTree test is reliably failing. @tli2 @malin1993ml

**Comment by apavlo** [comment]
Yes, we need to merge this to the project branch.

@yeshengm Can you post a separate issue for the failing bw-tree test?

**Comment by mbutrovich** [comment]
We have #264 open. I've still never seen it myself. If we can get logs I can probably enlist @wangziqi2013's help to look at it.

**Comment by yeshengm** [comment]
There's already one open issue #264 for BwTree.

**Comment by yeshengm** [comment]
@mbutrovich Run the test cases in debug mode and the bug appears. Otherwise in release mode the test cases just can't catch the bug.
