### ISSUE TITLE
terrier::common::NoMoreObjectException in LargeGCTests.HighAbortRateWithGC

### ISSUE THREAD

**Issue by DarkForte** [cmu-db/terrier#297]
(Migrated from Piazza)
Sometimes, my code (for branch 15721-s19-project1) in this test will throw the following exception:
![image](https://user-images.githubusercontent.com/8542129/52828730-f16a9600-3097-11e9-9fe8-c1c198e4cb44.png)
I see this under RelWithDebInfo build type (with my own project code). Is that the same problem from what Tianyu says below?

> "The test code assumes that there is at least one committed transaction when checking for correctness, but apparently contention is so high on that setting it could be that all the transactions were aborted. Thanks for spotting and we will fix this. Meanwhile, this shouldn't be an issue for the assignment I think."

**Comment by tli2** [comment]
Resolved on Piazza. Should tune up the number of max objects on larger machines,
