### ISSUE TITLE
Checkpoint and Recovery

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#304]
We left checkpoint and recovery unimplemented in the Fall because of the lack of catalog for recovery.

Our current system is essentially physical logging of all the redo records. The original plan was to implement consistent checkpoints by taking advantage of MVCC. On crash, the system reboots to a consistent point and replays the log in one pass, applying all the other committed changes.

One possible optimization to this is to allow checkpoints to be somewhat fuzzy. Specifically, the checkpoint does not need to be a consistent snapshot so long as all the values written out are committed, and their transactions have their log records on disk. The recovery pass can also be optimized in this case by keeping per-block metadata to skip applying certain regions of the log.

**Comment by pervazea** [comment]
There was discussion at team meeting on 30 Apr. of recovery and catalog interactions.

When recovery needs to be done, the sequence is:
- system starts up
- system catalog tables created, but not populated
- recovery will read the logs and populate the catalog tables. To insert data into the catalog tables, recovery needs to take the table oid and find the corresponding catalog table and schema.

Options:
1) Create a way for an oid encode the catalog table type. Something like:
If database oid = 1, then database local tables would be:
- oid 2 = pg_namespace
- oid 3 = pg_class
...

Possible, but not very clean.

2) If recovery has the option of recording not just the oid, but also the table type, by name or by enumerated value, then the schema  can easily be determined from the (oid, table type) pair. No changes would be needed to oid generation.
