### ISSUE TITLE
catalog:  convert to transient_value

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#310]
We started with Value, and TransientValue was created to replace it. The catalog code currently has both.

The catalog should switch over to using TransientValue and delete value.h and value_factory.h.
It is expected TransientValue will work fine for the catalog. Minor enhancements are fine, any major impediments should be raised for discussion.

**Comment by parsec0re** [comment]
The implementation is mostly done. We will close this issue once catalog is merged.
