### ISSUE TITLE
catalog: thread safety

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#311]
The one know issue, is that the maps in the catalog are not protected by locks. Discussed simply putting a lock around map access. The alternative of using a concurrent map was discussed.

To verify that we have no other concurrency bugs or design issues, a multi-threaded stress test for the catalog should be used. Deletion of catalog entries is only partially implemented. Until then, the test should only insert and verify.

**Comment by pervazea** [comment]
The other thing to examine is need for the maps. They are convenient, but... we have a ptr to the sql table helper, in the catalog. The maps facilitate doing lookups and eventually retrieving the storage ptr. Can this (should this) be done via the catalog? We discussed that the execution layer is not going to use the C++ catalog code, so all of the lookups that need to be done, must be possible via the catalog tables.

**Comment by yangjuns** [comment]
> The one know issue, is that the maps in the catalog are not protected by locks. Discussed simply putting a lock around map access. The alternative of using a concurrent map was discussed.
> 
> To verify that we have no other concurrency bugs or design issues, a multi-threaded stress test for the catalog should be used. Deletion of catalog entries is only partially implemented. Until then, the test should only insert and verify.

We didn't have a concurrent test for sql_table because it was a simple wrapper around DataTable, which has a concurrent test. I am adding a concurrent test for sql_table.h as I'm rewriting sql_table.h to support schema change. I believe there will be an overlap between the tests I'm writing and the one needed by the catalog.
