### ISSUE TITLE
catalog: CreateTable 

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#313]
TableHandle::CreateTable doesn't do everything that we need.

The above, creates a storage table and inserts a row into pg_class. (It returns a raw pointer, which is probably not ok).

We need, at a higher level, for creating tables to:
- from input of schema and table name, to create a storage table
- insert the name and ptr into pg_class
- insert the schema (i.e. column information) into pg_attribute, with the correct references to the pg_type for the column types
 - insert any column default values into pg_attrdef

**Comment by jrolli** [comment]
I don't think creation of the underlying storage should be the catalog's responsibility, but rather the execution engine's.

Specifically, I'm thinking that if we have a transaction doing a large DDL transaction it would be better to stage all of the catalog writes before doing any object creations.  This way if there is an error in the catalog phase (such as a namespace conflict) or competing DDL transactions, we abort before memory intensive operations like initializing SqlTables.

@mbutrovich, any thoughts?

**Comment by pervazea** [comment]
There are several issues here:
1. The issue talks about TableHandle. This is a view. My recollection is we were ok with views being read-only. If so, a CreateTable method doesn't really belong there.  The partial support for table creation that I describe is a problem.

1. We have CreateUserTable in catalog class, that does a reasonably complete creation, populating catalog information. This was to exercise the machinery, not expected to be the perfect final API. Your comment about separating storage creation is applicable here.
