### ISSUE TITLE
catalog: storage pointers and shutdown

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#323]
At the moment, the catalog uses shared ptrs to storage tables and stores are raw pointer to the storage table in pg_class.

We need to:
1. Switch to using raw pointers to storage tables.
2. Implement catalog shutdown, to safely shutdown.  The catalog does not know what transactions are active, nor does it know if the garbage collector is still accessing tables. Shutdown of the catalog should:
i) Wait for completion of all transactions
ii) Wait for the garbage collector to finish
Then, the catalog can delete both system and user tables safely.

**Comment by apavlo** [comment]
Shouldn't the GC delete the physical tables? It should be the same mechanism as DROP TABLE.

**Comment by pervazea** [comment]
You are correct. 
At a first read, I don't see support in the GC for this.

**Comment by pervazea** [comment]
Most of this work is now in the catalog branch.

- Shared ptrs to the SQL table helper have been replaced with raw pointers
- Shutdown of the system now deletes the SQL table helpers (and the sql table objects). This isn't coordinated with the GC yet.
