### ISSUE TITLE
JDBC support in Terrier

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#327]
Information about JDBC and Peloton, hopefully helpful for implementing and testing JDBC support in Terrier.

1. In the Peloton tree in: peloton/script/testing/junit are a set of Java tests that use the JDBC driver to send queries and check the results. They exercise prepared statements, with variations on INSERT, e.g. INSERT INTO tbl (c3, c1, c2) VALUES (?, ?, 2); Variations on data type, column ordering and ? vs fixed values (2). There were a number of cases that Peloton did not handle, that were fixed with the aid of these tests.

2. The tests permit control over the driver behavior. See PLTestBase.java, line 40
        // 0 => suppress switchover to binary protocol
        props.setProperty("prepareThreshold", "0");

We need to be able to support both text and binary protocol. A good starting point would be to exercise the JDBC protocol using just text protocol initially, then add in support for binary.

The run_junit.py script just facilitates running the tests, if you have a Peloton build. One can run the tests manually without it.

3. https://jdbc.postgresql.org/documentation
Provided useful information about the JDBC driver, as well as providing access to the source code. 

The prepareThreshold setting was the critical one last time, but there are many other configurable settings.

**Comment by DarkForte** [comment]
Apart from "junit", there is a "jdbc" folder in Peloton too. Do we need them?

**Comment by apavlo** [comment]
@DarkForte link?

**Comment by DarkForte** [comment]
https://github.com/cmu-db/peloton/tree/master/script/testing/jdbc

**Comment by apavlo** [comment]
These are the Java tests that I was talking about. We need to bring these over too.

**Comment by tli2** [comment]
These are already in.
