### ISSUE TITLE
CI Improvements

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/terrier#33]
The plan for our CI setup is:
**Travis:**

- [x] packages.sh
- [x] check-format
- [x] check-clang-tidy
- [x] lint
- [x] Doxygen
- [x] DEBUG: make

**Jenkins:**

- [x] DEBUG: make unittest (-DTERRIER_USE_ASAN=ON)
- [x] DEBUG: make unittest (-DTERRIER_GENERATE_COVERAGE=ON)
- [x] RELEASE: make unittest (-DBUILD_WARNING_LEVEL=Production)
- [x] RELEASE: make runbenchmark (-DBUILD_WARNING_LEVEL=Production)
- [x] performance and memory
- [ ] coveralls

TODO (me): quick script to fail build if coverage drops by 5%

**Comment by mbutrovich** [comment]
This issue is dependent on #38 being finished first. Should get that today.

**Comment by mbutrovich** [comment]
This issue is now dependent on #43 (make lint finds issues now).

**Comment by mbutrovich** [comment]
Blocked by #1
