### ISSUE TITLE
TPC-C benchmark

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#335]
We have indexes, we have logging, we have garbage collection. Now do something with them. Implement TPC-C exercising the concurrency control and storage layers (including indexes, logging, and garbage collection). This PR will track our implementation progress. WIP branch is [here](https://github.com/mbutrovich/terrier/tree/tpcc2).

**Table creation (Schema and SqlTable):**
- [x] Item
- [x] Warehouse
- [x] District
- [x] Customer
- [x] History
- [x] New Order
- [x] Order
- [x] Order Line
- [x] Stock

**Table population:**
- [x] Item
- [x] Warehouse
- [x] District
- [x] Customer
- [x] History
- [x] New Order
- [x] Order
- [x] Order Line
- [x] Stock

**Index creation (IndexKeySchema and Index):**
- [x] Item
- [x] Warehouse
- [x] District
- [x] Customer
- [x] Customer secondary (Payment and Order Status)
- [x] New Order
- [x] Order
- [x] Order secondary (Order Status)
- [x] Order Line
- [x] Stock

**Index population:**
- [x] Item
- [x] Warehouse
- [x] District
- [x] Customer
- [x] Customer secondary (Payment and Order Status)
- [x] New Order
- [x] Order
- [x] Order secondary (Order Status)
- [x] Order Line
- [x] Stock

**Workload generation:**
- [x] New Order
- [x] Payment
- [x] Order Status
- [x] Delivery
- [x] Stock Level

**Workload execution:**
- [x] New Order
- [x] Payment
- [x] Order Status
- [x] Delivery
- [x] Stock Level

**Test Framework:**
- [x] Builder
- [ ] Stats
- [x] Parallelized transaction execution
- [x] Documentation

**Nice to have:**
- [ ] [done but don't want it right now] Parallelized table and index population
- [x] Minimize type sizes in table schemas

**Comment by mbutrovich** [comment]
With 5 of the 9 tables down I think I've implemented all of the boilerplate needed for the various types of random attributes by now and can crank out tables pretty quickly now. I expect all 9 will be done tomorrow, and I can sync up with @lmwnshn to see how the indexes are looking.

**Comment by mbutrovich** [comment]
All of the tables have been instantiated and loaded per TPCC spec. I just finished defining all of the index key schemas and instantiating the indexes. Just need to modify the loader to insert into the indexes as well.

**Comment by mbutrovich** [comment]
All of the indexes are loaded per TPCC spec. In theory it's time to move on to implementing New Order.

**Comment by mbutrovich** [comment]
Relatively set with the code structure of a transaction now after implementing New Order. @lmwnshn will start working on Delivery following that model while I look at Payment and Order Status.

Current number is ~80,000 New Orders per second on my laptop with scale factor 4.

**Comment by mbutrovich** [comment]
New Order and Payment are done. The other transaction types need index scans rather than just point queries (only the latter is implemented in the system right now), so @lmwnshn and I will take a look at what it's going to take to implement the necessary index functionality.

**Comment by mbutrovich** [comment]
Now that we have basic index scan support, I added the secondary index that Order Status wants and implemented Order Status.

**Comment by lmwnshn** [comment]
Re: nice to have, I already have parallelized loader sitting in a commit. (this was before the new secondary index, just minor changes). So I went ahead and ticked that off.

Delivery should also be fine now. We should talk stats.

**Comment by mbutrovich** [comment]
Fixed up Delivery and Order Status, and modified New Order to not insert into indexes until it's guaranteed to commit. This solves the index pollution issue caused by aborts that was making the other queries problematic. Just Stock Level left, which I believe is the easiest transaction to implement.

**Comment by lmwnshn** [comment]
Ticked StockLevel.

**Comment by mbutrovich** [comment]
The leak looks to be inside the BwTree. I emailed @wangziqi2013 to see if he has some time to look at it with me.

**Comment by mbutrovich** [comment]
LSAN log from dev4 is attached. Still trying to make sense of it with @wangziqi2013.

[lsan.txt](https://github.com/cmu-db/terrier/files/3103830/lsan.txt)

**Comment by mbutrovich** [comment]
Besides the memory leak in the BwTree, there's no PR for this yet because we need #356 and #360 to merge first. From an implementation standpoint, I believe we're done.

**Comment by mbutrovich** [comment]
I wrote a unit test that seems to reproduce the memory leak regularly on dev4 without having to run all of TPC-C. It sort of emulates the New Order index behavior: threads inserting, threads scanning and then deleting the smallest element of their scan results. It’s in this branch:

https://github.com/mbutrovich/terrier/tree/bwtree_memory_leak

Test is here:

https://github.com/mbutrovich/terrier/blob/bwtree_memory_leak/test/storage/bwtree_test.cpp#L26

@wangziqi2013 will look at it in a few days when he has time.
