### ISSUE TITLE
Defining terrier::parser:: Parameter twice

### ISSUE THREAD

**Issue by Chenyao2333** [cmu-db/terrier#343]
These two places all have `terrier::parser::Parameter` definition. They may never be compiled together before.

https://github.com/cmu-db/terrier/blob/master/src/include/parser/create_function_statement.h#L19

https://github.com/cmu-db/terrier/blob/master/src/include/parser/parameter.h#L9

**Comment by lmwnshn** [comment]
This looks to be weird legacy stuff that I think we didn't pay much attention to (UDFs).

Are UDF parameter datatypes the same as our SQL ones? Looking back at the [Peloton](https://github.com/cmu-db/peloton/blob/master/src/include/parser/create_function_statement.h#L54) code it came from, it seems that we should get rid of the first completely.

**Comment by lmwnshn** [comment]
As a temporary solution, rename the first to FunctionParameter.

**Comment by Chenyao2333** [comment]
I rename the first one to `BaseFunctionParameter` because [there](https://github.com/cmu-db/terrier/blob/master/src/include/parser/parsenodes.h#L809) already define `FunctionParameter`. It will merge into Gus's JSON branch. So this issue can be solved as this pr https://github.com/cmu-db/terrier/pull/334 be merged.

If anyone has the same problem, I can submit a pr to address this.
