### ISSUE TITLE
catalog: use of maps

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#347]
See also issues #311 and #323. 

At time of writing, the catalog code uses two maps to facilitate lookup of information. All the information is in the catalog tables, but lookup in the catalog is more cumbersome and probably slower. The maps are a convenient cache for some operations.

Problems:

- The maps do not consider thread safety. They probably need locking added to ensure thread safety (or use some form of lock free structure).
- After recovery, the maps content would need to be reconstructed. The catalog doesn't support recovery yet.
- Lin raises a question whether the maps will work with multi-version schemas? I don't know enough about where the multi-version schema design stands. My understanding is that the schema versioning will be done under the sql table layer. The maps hold no schema information, but do hold information about table existence. Is this a problem? (Seems like it could be).

It is possible to eliminate the maps and use the catalog tables themselves.

**Comment by pervazea** [comment]
After looking at the maps further last week, my conclusion is that the maps are problematic and need to be removed.

1. The maps bypass the namespace. This requires some care in their use, but isn't a fatal flaw.
2. The maps bypass the transaction manager. So, the following scenario would be a problem:
- Transaction A creates a table X, and inserts in to the maps. Does not commit yet.
- Transaction B looks up table X. It will be visible. It should not be.

The opposite scenario of deleting a table, is similarly a problem.
If lookups are done using the catalog tables and transactions, the semantics will be correct.

3. Outside of the maps, it is not possible to look up instances of the catalog classes. We embed a pointer to the storage table helper in pg_class, but pointers to other classes are required, e.g. the namespace. This will need to be fixed as part of addressing this issue.

**Comment by jrolli** [comment]
I think the thread safety is the most immediate problem with this since inserts and deletes can invalidate all concurrent iterators (to include the ones implicit in `find` and `at`) which could cause segfaults if a table is done concurrently with binding in particular.
