### ISSUE TITLE
BwTreeIndex reads aware of concurrency control

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#357]
In Peloton the Scans, ScanLimit, etc. functions of the index wrapper were not aware of concurrency control semantics. For example if you had a scan with limit 10, you could get 10 values back from the BwTreeIndex that when you went to the DataTable to perform an operation could result in tuples that were not actually visible to your transaction. I'm not sure how the execution layer handled this in Peloton (perhaps it repeated scans with offsets until the query conditions were satisfied), but we should discuss if this should be handled in the BwTreeIndex class. The SqlTable provides a view of the storage layer that abstracts away concurrency control knowledge, only ever presenting visible tuples to the execution layer.

If we wanted to copy that model for BwTreeIndex, operations would need to take in a TransactionContext and perform a visibility check on corresponding TupleSlots in DataTables, and then only provide visible results. This is already how primary key enforcement was implemented in Peloton (ConditionalInsert with a predicate function passed in to the BwTree to hit the DataTable for a visibility check) so it doesn't seem unreasonable to extend concurrency control knowledge to other BwTreeIndex operations. The downside is an extra trip to the DataTable for any index operations before presenting results to the user. The hope would be that we could avoid any materialization, however, by adding a Select-like method that only traverses the version chain (short in expectation) long enough for visibility to be determined.

**Comment by apavlo** [comment]
Let's discuss this today. Remind me

**Comment by mbutrovich** [comment]
Answer: yes, do the dang thing.

**Comment by mbutrovich** [comment]
Fixed by #356.
