### ISSUE TITLE
NameToOid() in catalog branch has segFault when the name is not inserted

### ISSUE THREAD

**Issue by yangdsh** [cmu-db/terrier#365]
In many classes, the NameToOid() function calls GetXXXEntry() function. If the name we query is not inserted, the GetXXXEntry() will return a nullptr, and NameToOid() will get segFault when using that nullptr.  

For example, you can refer to GetNamespaceEntry() and NameToOid() in namespace_handle.cpp.

**Comment by pervazea** [comment]
Pushed fixes into the catalog branch.

- name to oid conversions will generate a catalog exception if the name does not exist.
- lookups for non-existent items, i.e. GetXXXEntry methods return a nullptr.

**Comment by pervazea** [comment]
Should be addressed in the catalog branch code, now merged. Please re-open if it does not.

**Comment by pervazea** [comment]
Discussed in the team meeting, preference for returning an error value rather than an exception.
