### ISSUE TITLE
CMake cleanup

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/terrier#38]
At some point, we should decide what we want to keep/remove (e.g. make lint).

**Comment by mbutrovich** [comment]
- make lint: it's specific to Google's code style, and I believe we can get the same if not even more restrictive checks via clang-format and clang-tidy. Propose to remove.
- make infer: it's an [interesting static analysis tool from Facebook](http://fbinfer.com). I just installed and ran it to see what it found on the codebase to see what it found. [Here are the results.](https://github.com/cmu-db/terrier/files/2242654/bugs.txt). We should discuss if we want to integrate it into our automation.
