### ISSUE TITLE
Catalog Limits Tables to 100 MiB

### ISSUE THREAD

**Issue by jrolli** [cmu-db/terrier#380]
Currently the catalog handles allocation and initialization of the storage backend for SQL tables (i.e. `storage::SqlTable` instances).  It allocates these instances through its own wrapper that provides it a hard-coded block store with a max size of 100 (i.e. it can allocate up to 100x 1 MiB blocks).

The long-term solution for this is to separate "logical" creation of the table in the catalog from the "physical" creation of the storage object.

**Comment by pervazea** [comment]
This was on the todo list, and obviously only satisfactory for unit testing. 

The question of how many block stores, was discussed a bit, but not resolved. Possibly for catalog internal tables, there should be a single (configurable size) block store, and a separate one for user tables. Not sure what the correct answer is.

**Comment by apavlo** [comment]
@tli2 @mbutrovich I thought that there was already single block store for the system? Catalog tables are just tables. They shouldn't be treated differently.
