### ISSUE TITLE
Change AbstractExpressions to raw pointers to better control their lifecycle

### ISSUE THREAD

**Issue by GustavoAngulo** [cmu-db/terrier#384]
@jrolli brought up the issue of being unable to store smart pointers in the catalog. This causes issues when trying to store `AbstractExpressions`. After discussing it with @jrolli and @mbutrovich, we agreed that we should store `AbstractExpression`s as raw pointers to have more fine grained control of its lifecycle.

**Comment by mbutrovich** [comment]
They were made into ManagedPointers instead.
