### ISSUE TITLE
Test running two DBMains in the same process

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#393]
We now added the ability to start/stop the DBMS using the `DBMain` class. This means that in theory we should be able to run two DBMS instances together at the same in the same process.

A first simple test case to write is to check whether we can start/stop two `DBMain` at the same time. Create a new test case file `test/main/db_main_test.cpp` and add it there. You will need to change the port number in the settings map that you pass in so that each `DBMain` listens on a different port.

Then once the networking PR is merged (#328), we should be able to expand the test and load in different data two each `DBMain` instance and check that we can connect to each instance separately without interference.

**Comment by makleboss** [comment]
Yes

**Comment by apavlo** [comment]
I think this works now in #648
