### ISSUE TITLE
Remove singleton DedicatedThreadRegistry

### ISSUE THREAD

**Issue by GustavoAngulo** [cmu-db/terrier#418]
Currently the DedicatedThreadRegistry is a [singleton](https://github.com/cmu-db/terrier/blob/025d906a353430700bd4376fa066b3d7849b2ef8/src/include/common/dedicated_thread_registry.h#L48). We want to get rid of it because we hate singletons.

**Comment by GustavoAngulo** [comment]
I believe @mbutrovich took the lead on this.

**Comment by mbutrovich** [comment]
Yep I've got a fix in my MetricsManager branch. It can probably wait for that to be merged rather than cherry-picking it.
