### ISSUE TITLE
"You know what this is... "

### ISSUE THREAD

**Issue by jorgerpo** [cmu-db/terrier#431]
I have no idea.

What is this?

**Comment by apavlo** [comment]
Thanks for getting in touch. This video should explain everything:

https://youtu.be/CqkEuUuQQWs

-- Andy

**Comment by brianfay** [comment]
For some reason Github's recommendation algorithm really likes this repository; I see this show up probably at least once a week:
<img width="330" alt="Screen Shot 2019-09-26 at 11 17 24 AM" src="https://user-images.githubusercontent.com/2925265/65722512-606e8b00-e07a-11e9-9c01-90a1012fb34f.png">

If the CMU db group is interested in sharing its work with the public, that's pretty cool. But here I get the sense that any actual interest from the public will be flippantly discouraged.

**Comment by apavlo** [comment]
@brianfay We're getting closer to announcing this and changing the name. I agree that the current situation is not ideal.
