### ISSUE TITLE
Helper Function to Extract Referenced Column Oids from AbstractExpression Tree

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#437]
The optimizer cannot assume that an index's schema contains a one-to-one mapping from key attribute to column oid. This is because you can have indexes like this:

```sql
CREATE INDEX ON xxx (col1 + 1, col2 + col3);
```

@17zhangw needs a helper method that recursively traverses an `AbstractExpression` tree and returns a set of the referenced `catalog::col_oid_t` values in the tree.

This should be done **after** we rename `TupleValueExpression` in #404.

## Instructions

1. Create a new `ExpressionUtil` class in 'src/include/parser/expression/expression_util.h'.
   See [`HashUtil`](https://github.com/cmu-db/terrier/blob/master/src/include/common/hash_util.h) for what these classes look like.

2. Create a static method called `GetColumnOids`:
    ```c++
    static void ExpressionUtil::GetColumnOids(std::set<catalog::col_oid_t> &col_oids, managed_ptr<AbstractExpression> exp) {
    ...
    }
    ```
    This method should recursively call itself for the left/right children (if not null) and populate the `col_oids` set from `TupleValueExpression` objects (this will change after #404).

3. Write a set of test cases in 'test/parser/expression_util_test.cpp'. See other test cases on how to create test `AbstractExpression` objects and run the tests.

**Comment by jbx7106** [comment]
Hi apavio I'm a beginner. Would you assign this task to me?

**Comment by apavlo** [comment]
@jbx7106 Go for it! I've updated the issue with instructions. Send us as pull request when you're ready. See these instructions on how to do that:

https://github.com/cmu-db/terrier/wiki/Pull-Request-Process

**Comment by apavlo** [comment]
@jbx7106 See this incomplete method from the old code:

https://github.com/cmu-db/peloton/blob/master/src/include/expression/expression_util.h#L349-L385

This is not exactly what we want but it should give you the basic idea.

**Comment by jbx7106** [comment]
Great. Thanks, @apavlo I look forward to contributing. :)
