### ISSUE TITLE
Logical + Physical Operators for Create and Drop

### ISSUE THREAD

**Issue by 17zhangw** [cmu-db/terrier#484]
Currently we don't have logical/physical operators for `CREATE` and `DROP` but we do have the plans (i.e `src/include/planner/plannodes/create_*.h` and `src/include/planner/plannodes/drop_*.h`).

Ideally for create/drop operations, the optimizer should take in a logical operator, convert it to a physical operator, and then emit the correct plan (as opposed to special casing in Peloton). To do this, we need logical + physical operators for `CREATE` and `DROP` that contain all the information required by the plan nodes.

**Comment by apavlo** [comment]
@zhou0ricky Start with `CreateDatabasePlanNode`

1. Look at the create plan nodes to see what meta-data they store:

https://github.com/cmu-db/terrier/blob/master/src/include/planner/plannodes/create_database_plan_node.h#L111

2. Add new logical operators to this file: https://github.com/cmu-db/terrier/blob/master/src/include/optimizer/logical_operators.h

3. Add new physical operators to this file: https://github.com/cmu-db/terrier/blob/master/src/include/optimizer/physical_operators.h
