### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by pervazea** [cmu-db/terrier#49]
I've looked at what we've added into the repo for debug logging. The recommendation of how we expect developers to use the logging features was not at all clear. Like everyone else, I can read code and figure this out, but was looking for the "new developers guide to logging". We don't have that yet.

It raises the question of whether we even have agreement and understanding of what we need. Possibly what we've added, is not the right solution.

So, lets discuss requirements and use cases.  

The style of debug logging we have in Peloton, is widely used. Many implementations pair the LOG calls with multiple back end implementations, so you can log to stdout, files or network sockets. We use it only for stdout, so it is a more structured way of doing printfs. So, what is wrong with what we have in Peloton?

1. We have not applied consistency to what we log and when we log it.
1. At LOG_INFO, we don't log much, but some of what is logged is not useful.
1. At LOG_DEBUG it is a free for all. Some log points provide useful information, others don't. Often the log information is only useful to the developer who implemented it or needs additional knowledge of the code path to make any sense of the output. 
1. At LOG_TRACE, the volume of output is so high, it is IMO practically useless. LOG_TRACE is inconsistently used to trace function calls. There are better ways of doing this.
1. There is no way to reduce the noise level and zero in on the component you are developing or debugging. You get all LOG_DEBUG messages or none. 

Questions
1. What do we want to get from debug logging?
1. What set of features do we want?
1. What controls / knobs do we want?

Opinions
1. Debug logging as a structured way of printing information is OK.
1. Having multiple back ends would be nice, but is not required. Just printing is usable.
1. We need guidelines on what is appropriate in the different log levels.
1. We need guidelines on what to put in log messages, and enforce this in code reviews. 
1. In addition to the log level to be output, we need to be able to control logging "per module". This could be:
  1. Per "module", e.g. per namespace
  1. Per module, where it is some other module notion that we encode
  1. Per file.
1. Compile time selection of what is logged, is usable. Run time enable / disable of module logging is desired, possibly required.
1. Control of logging via API, at run time, would be very useful. When debugging, this would allow logging to turn on only when some interesting condition or state is entered.
1. Control of logging via GDB is useful. Control via some admin user interface is better, but is unlikely in the near future.
1. You should be able to completely eliminate overhead when not using it. The Peloton logging does this by providing an empty macro body when you turn off a log level.
1. Gcc can compile code that includes hooks for function entry/exit, according to the documentation. Function tracing should use this facility as a compile variant, rather than us manually inserting function entry / exit LOG points.

I was hoping that easylogging would provide a suitably lightweight framework, which could be wrapped to provide a small, controlled subset that fit our needs. I can't tell if it does or not. 

Alternatively, if we were rolling our own, a possible approach is as follows. It is very basic and very minimal, and just slightly extends what we've been using. 

Outline
1. Start with the Peloton logging macros, i.e. keep the notion of:
   1. LOG_INFO
   1. LOG_DEBUG 
   levels etc.

1. Document what is appropriate for each level.
1. Document and enforce what goes into log messages. The purpose here is to avoid, useless log points being inserted. 
1. Extend the macros to include a module. For the moment lets assume modules map roughly to a namespace, but possibly finer granularity, defined by us.
1. A log point might look like:
    LOG_DEBUG(MODULE_NETWORK_MARSHALLING, "output binary %d", var);

1. If we could live with 64 modules max, the modules could be encoded as bits, e.g.
    #define MODULE_NETWORK_MARSHALLING 0x1
    #define MODULE_NETWORK_PARSING 0x2
    and so on
    If we want more than 64 modules, then you do a lookup rather than a bit mask, so marginally
    more complex. 

1. Log macros would then be roughly:
    if ( log_enabled_var & MODULE_XXX) then LOG_DEBUG_NO_MODULE(string, varags)

1. Couple with some additional macros and / or APIs to control logging at runtime.

Now, this is the familiar approach. The disadvantage to this is printing to stdout is not cheap. It slows down the system significantly and therefore changes timing. Problems that occur at high load when running at high performance, sometimes (frequently?) can't be debugged this way.

Therefore it may be necessary, at some point, to supplement debug logging with "high performance tracing". It may be a long way in the future. I note here just to raise awareness that debug logging is not the end of the story.
This is an old technique for debugging devices drivers, kernel modules etc. The outline being:
1. Create a "large" memory buffer. Used as a circular buffer.
1. Insert log points that insert items into the memory buffer. Typically binary information only. Log point identifier, values to save for the log point.
1. When needed, after some event of interest, programmatically dump the buffer.
1. Use associated utility to decode the contents of the buffer.
1. This is of course, extremely fast but not so easy to use.

Back to debug logging. Comments?

**Comment by pervazea** [comment]
Searching yesterday, for additional (possible) choices. Look possible, need careful evaluation.

- [spdlog]( https://github.com/gabime/spdlog)
- [llcpp](https://github.com/blapid/llcpp)
- [boost logging](https://www.boost.org/doc/libs/1_63_0/libs/log/doc/html/index.html)  
- [easylogging]( https://github.com/easylogging )

Rolling our own is also possible.

**Comment by pervazea** [comment]
Google logging, glog?

**Comment by crd477** [comment]
If neither spdlog or easylogging pan out, two more candidates might be:

- [log4cxx](https://logging.apache.org/log4cxx/latest_stable/index.html): Apache log4cxx is a logging framework for C++ patterned after Apache log4j  (Apache license)
- [Pantheios](http://www.pantheios.org/): Diagnostic Logging API library, offering a combination of type-safety, efficiency, genericity and extensibility (BSD license)

**Comment by mbutrovich** [comment]
Fixed by #92.
