### ISSUE TITLE
Probable Race Condition in Block Access Controller

### ISSUE THREAD

**Issue by jrolli** [cmu-db/terrier#490]
Summary: When compiled for release there appears to be an infrequent race condition that will cause the BlockAccessControllerTest to fail the assertion on line 116 which ensures that WaitUntilHot will guarantee all locks are released before making a block hot.

### Test results
```
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from BlockAccessControllerTest
[ RUN      ] BlockAccessControllerTest.SingleReader
[       OK ] BlockAccessControllerTest.SingleReader (0 ms)
[ RUN      ] BlockAccessControllerTest.WriterPreemption
[       OK ] BlockAccessControllerTest.WriterPreemption (0 ms)
[ RUN      ] BlockAccessControllerTest.FreezingBlocksBoth
[       OK ] BlockAccessControllerTest.FreezingBlocksBoth (11 ms)
[ RUN      ] BlockAccessControllerTest.ReaderWriter
[       OK ] BlockAccessControllerTest.ReaderWriter (11 ms)
[ RUN      ] BlockAccessControllerTest.MultipleReaders
../test/storage/block_access_controller_test.cpp:116: Failure
Value of: REACHED(reader1_released) && REACHED(reader1_released)
  Actual: false
Expected: true
[  FAILED  ] BlockAccessControllerTest.MultipleReaders (17 ms)
[----------] 5 tests from BlockAccessControllerTest (39 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (39 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BlockAccessControllerTest.MultipleReaders
```

### Steps to reproduce:
```bash
cmake -DCMAKE_BUILD_TYPE=release -DTERRIER_USE_ASAN=off -DBUILD_WARNING_LEVEL=production
make -j
release/block_access_controller_test --gtest_repeat=-1 --gtest_throw_on_failure
```

### Notes:
Building in release mode results in the following warnings:
> ../src/include/storage/block_access_controller.h: In member function ‘std::pair<terrier::storage::BlockState, unsigned int> terrier::storage::BlockAccessController::AtomicallyLoadMembers()’:
> ../src/include/storage/block_access_controller.h:128:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      return *reinterpret_cast<std::pair<BlockState, uint32_t> *>(&curr_value);
>                                                                             ^
> ../src/include/storage/block_access_controller.h:128:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
> ../src/include/storage/block_access_controller.h: In member function ‘bool terrier::storage::BlockAccessController::UpdateAtomically(const std::pair<terrier::storage::BlockState, unsigned int>&, std::pair<terrier::storage::BlockState, unsigned int>)’:
> ../src/include/storage/block_access_controller.h:134:63: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>          expected_bytes, *reinterpret_cast<uint64_t *>(&desired));
>                                                                ^

### Initial suspicions:
We are using a struct of two `uin32_t`s to pass the 64-bit type value, which means the values are not guaranteed to be placed 64-bit aligned.  This could cause us to lose the atomicity we are expecting in the code.

**Comment by tli2** [comment]
I can take a look at it later. Suspicion about alignment could be right, but we place the control block manually in a storage block, so I will have to double check.

Also, reminds me of this. Although unlikely to be source of this particular bug.
https://github.com/cmu-db/terrier/issues/402

**Comment by tli2** [comment]
@jrolli The bug seems to be a race in the test case itself. The code looks fine.

https://github.com/cmu-db/terrier/blob/master/test/storage/block_access_controller_test.cpp:

master         reader1        reader2
line 115
                       line104         line111
line 116 <----- X
                       line105          line112

There doesn't seem to be a way to exactly test for correct behavior, other than pushing the program points for release before the actual release. At least that way we don't fail spuriously. (Tried it and it worked)

**Comment by jrolli** [comment]
That makes more sense then an alignment issue.  Should we move the release point and put a timed sleep/wait command in between the two program points to try and force the main thread to hit WaitUntilHot while both readers have the lock?
