### ISSUE TITLE
doxygen false alarm

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#515]
Most likely the regex matcher doxygen uses does not handle macros properly. In https://travis-ci.org/cmu-db/terrier/jobs/572942392, it mistakenly thinks that the initializer list is a bunch of undocumented members.

This is currently more of a nuisance than a bug. Inserting an extra newline character in the parameters fixes the issue.

**Comment by mbutrovich** [comment]
I think this was an artifact of the Boost::DI stuff, so going to close it.
