### ISSUE TITLE
Integrate sample TPL program testing into build process

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/terrier#517]
In order to maintain a stable execution engine, we need to incorporate testing the sample TPL programs into part of the build process. Especially, we want to test all the three execution modes (`interpret`, `JIT`, and `adaptive`) with all different compilation flags (`debug`, `release`, `relwithdebinfo`) to make sure that the programs successfully run and return the correct results.

**Comment by mbutrovich** [comment]
I believe this is now handled by the `check-tpl` target.
