### ISSUE TITLE
Actions in DeferredActionManager can appear out of order

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#520]
With #441 decoupling actions into a separate component, it is no longer protected by the commit latch in the transaction manager. There is now possible out-of-order execution of the action queue.

We (me and jrolli) think that it does not matter, but we are not sure. It will be nice to take some time to investigate and verify that this is fine.

**Comment by jrolli** [comment]
For future discussion, the specific conditions for out-of-order execution of events in the action queue the following events must occur:

1. Thread T1 fetches a timestamp in `deferred_action_manager.h:RegisterDeferredAction` and starts spinning on the spin latch
2. Current timestamp advances (reason does not matter)
3. Thread T2 comes through fetches a timestamp (higher than T1's), wins the race for the spin latch, and successfully enqueues its actions.
4. GC activates and wins the race for the spin latch, enqueueing T2's actions but not T1's.
5. T1 wins the spin latch and enqueues its actions.
6. GC activates with an oldest running transaction time later than T1's but newer than T2's action timestamps.  It does not execute T2's, but when it pulls the new timestamps from the deferred action manager, it does replay T1's.

The only case where I can think this may allow unsafe memory access is if T1 drops an index from which T2 deletes.  However, I have not done an in depth code review to see if this exact ordering is possible for that situation.

**Comment by tli2** [comment]
I believe #526 now requires this to be fixed

**Comment by yash620** [comment]
A fix for this is in DeferredActionsManager::Process to to only call ProcessNewActions if the backlog is empty.
