### ISSUE TITLE
Check for Case in Class/Method/Member Names

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#523]
@tli2 correctly points out [here](https://github.com/cmu-db/terrier/pull/516#issuecomment-524310774) that we are not checking for the proper capitalization in the code.

* **CamelCase**: Functions + Classes
* **snake_case_**: Class Members (with underscore prefix)
* **snake_case**: Local Variables (no underscore prefix)

We need to figure out a way to do this automatically with clang.

**Comment by mbutrovich** [comment]
It should just be a matter of specifying the options for this check in the repo’s .clang-tidy file.

http://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html

In theory we have the check enabled, but I suspect if you don’t actually specify what rules you want the codebase to conform to then it doesn’t flag anything.

**Comment by mbutrovich** [comment]
Add this:
```
CheckOptions:
  - { key: readability-identifier-naming.ClassCase,           value: CamelCase  }
  - { key: readability-identifier-naming.EnumCase,            value: CamelCase  }
  - { key: readability-identifier-naming.FunctionCase,        value: CamelCase  }
  - { key: readability-identifier-naming.GlobalConstantCase,        value: UPPER_CASE }
  - { key: readability-identifier-naming.MemberCase,          value: lower_case }
  - { key: readability-identifier-naming.NamespaceCase,       value: lower_case }
  - { key: readability-identifier-naming.PrivateMemberSuffix, value: _          }
  - { key: readability-identifier-naming.StructCase,          value: CamelCase  }
  - { key: readability-identifier-naming.UnionCase,           value: CamelCase  }
  - { key: readability-identifier-naming.VariableCase,        value: lower_case }
```
to the .clang-tidy file. As expected, it finds lots of failures. I'll open a PR so people can see what it yells about and we can decide as a group if that's how we want the code refactored.
