### ISSUE TITLE
Internal Terrier Protocol

### ISSUE THREAD

**Issue by GustavoAngulo** [cmu-db/terrier#537]
The first step to having replication is having a network protocol that can speak between terrier nodes. This is different from the postgres protocol that sends queries to the master node (although the two can have similarities in how they serialize data). The current name for this new protocol is Internal Terrier Protocol (**ITP**). 

The system should be able to support both protocols simultaneously by listening on two separate sockets. The reason that we have two separate protocols is so in the future, one can be changed without affecting the other. As we write ITP, we might realize that we are essentially writing the postgres protocol again. Thats ok. We still need to have them be separate protocols because in the future if we ever decide to ditch the postgres protocol, we can do so without having to rewrite ITP.

ITP will also have a separate set of commands (`AbstractNetworkCommands`) from the postgres commands. The first command we will need is a replication data command. I envisioned the packet looking like:

```
--------------------------------------------------------------------------------------------------
| message type (char) | message id (uint64_t) | data size (uint64_t) | replication data (varlen) |
--------------------------------------------------------------------------------------------------
```
`AbstractNetworkCommands::Exec` takes in a reference to the `TrafficCop`, which will handle the forwarding of the replication data to the `RecoveryManager`.

We will also need a Util class (static methods will do) that can make ITP packets and establish ITP connections. This will be used by the node that wishes to send messages. 

The first stab at implementing ITP is in my branch [here](https://github.com/GustavoAngulo/terrier/tree/internal_terrier_protocol). The first step is to allow for arbitrary protocols to be added by creating abstract classes, which I have begun to do, but not completely finished. After that, we need to implement the different commands we need. Finally, as mentioned above, we will need a util class to establish connections and construct messages.

**Comment by mbutrovich** [comment]
@GustavoAngulo @tpan496 Was this fixed by #602?
