### ISSUE TITLE
Port IndexWrapperBenchmark

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#567]
@mbutrovich has a simple microbenchmark to evaluate the performance of our [index wrapper implementations](https://github.com/cmu-db/terrier/blob/master/src/include/storage/index/index.h):

https://github.com/mbutrovich/terrier/blob/24858ed974421a89950a409d257b5e5edeee74c0/benchmark/storage/index_benchmark.cpp

We need to bring this into our master branch and start running this in our nightly performance checks.

1. Create a new branch that just includes [index_benchmark.cpp](https://github.com/mbutrovich/terrier/blob/24858ed974421a89950a409d257b5e5edeee74c0/benchmark/storage/index_benchmark.cpp) in `terrier/benchmarks/storage`. We should rename this to `index_wrapper_benchmark.cpp` to make it clear that it is not meant to be an all inclusive benchmark for all of the indexes.

2. Modify the [nightly script](https://github.com/cmu-db/terrier/blob/master/script/micro_bench/run_micro_bench.py) to include your new benchmark code. Search for `large_transaction` in the file to find the two arrays that you need to modify (or the single array after #564 goes in).

**Comment by apavlo** [comment]
I forgot to mention that we should also re-enable the `HashIndexRandomScanKey` test:

https://github.com/mbutrovich/terrier/blob/24858ed974421a89950a409d257b5e5edeee74c0/benchmark/storage/index_benchmark.cpp#L153

**Comment by thepinetree** [comment]
Merged
