### ISSUE TITLE
Travis OSX Builds are Broken

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#571]
Brew is trying to install `bcel-6.3.1-bin.tar.gz` but the file is no longer available:

https://travis-ci.org/cmu-db/terrier/jobs/590848268#L1756
https://www-us.apache.org/dist/commons/bcel/binaries/bcel-6.3.1-bin.tar.gz

Somebody with a Mac is going to have to look into this.

**Comment by mbutrovich** [comment]
Linked in Slack a few days ago, but these are the issue and PR to watch:

https://github.com/Homebrew/homebrew-core/issues/44608
https://github.com/Homebrew/homebrew-core/pull/44581

I'm voting that this is not our problem to fix. As I said in Slack, we end up getting Mac coverage on Jenkins anyway, and we're looking at eventually deprecating Travis too. Recommend not putting any time into this.

**Comment by mbutrovich** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/44581
