### ISSUE TITLE
Bump LLVM to 9.0.0

### ISSUE THREAD

**Issue by yeshengm** [cmu-db/terrier#575]
LLVM on macOS was accidentally bumped to 9.0.0 by brew, and the current build infra is not working. To otherwise have another old version, we need `LLVM_DIR` set to `/usr/local/Cellar/llvm@8/8.0.1` by pinning an old version of LLVM.

**Comment by mbutrovich** [comment]
This was fixed last week by #559. Are you proposing moving to LLVM 9? The issue title is confusing.
