### ISSUE TITLE
Compilation fails on GCC8+

### ISSUE THREAD

**Issue by pmenon** [cmu-db/terrier#624]
Noticed the project is failing compilation on GCC8, the default on Ubuntu flavors 19+. I tried to solve them, but there are quite a few and in places that have non-trivial fixes. Not urgent, creating to track.

I also noticed that we're pulling in third-party sources into main compilation. This will most likely cause issues since different projects assume different compiler flags. For example, the `madoka` project fails compilation on GCC8+, too. We should probably be building them separately and linking them in to save ourselves the headache.

**Comment by mbutrovich** [comment]
I suspect this will not be heavily investigated until next summer when we'd want to move the default environment to the next Ubuntu LTS release (20.04) and whatever its default toolchain versions (GCC, Clang, LLVM) are and fix any of the compatibility issues in one shot then.

**Comment by mbutrovich** [comment]
Fixed by #642. As long as GCC 7 is the only version in CI though, we're likely to continue breaking compatibility.
