### ISSUE TITLE
We have two timers that do effectively the same thing

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#626]
`src/include/common/scoped_timer.h` and `src/include/execution/util/timer.h`. These should be combined under `common`.

**Comment by pmenon** [comment]
Whoever works on this can also fix this misspelling: https://github.com/cmu-db/terrier/blob/master/src/include/execution/util/timer.h#L48

**Comment by shubhamtomar95** [comment]
should the classes be merged under the namespace terrier::common or should the functions be moved to one of the classes if so which one will move  into which one?
And what about the methods that are calling one of these?

**Comment by pmenon** [comment]
The file under `execution` has `Timer` and `ScopedTimer`, both of which are needed. The `ScopedTimer` API is the same. I'd say move `src/include/execution/util/timer.h` to `src/include/common/scoped_timer.h` under namespace `terrier::common`. You'll need to modify call-sites to account for the namespace change.

**Comment by shubhamtomar95** [comment]
There is mismatch in the constructors of scoped_timer in the one under `execution`  and the one under `common` one.

https://github.com/cmu-db/terrier/blob/master/src/include/execution/util/timer.h#L71

https://github.com/cmu-db/terrier/blob/master/src/include/common/scoped_timer.h#L25

Do we need to keep both the classes under their respective namespace?

**Comment by pmenon** [comment]
Both classes should be under `terrier::common`. 

I'm indifferent as to whether to use `double` or `uint64_t` for timings. Floating point numbers seem natural, intuitive, and precise (e.g., 1.4 seconds vs 1 or 2 seconds). I'll let others chime in.

**Comment by mbutrovich** [comment]
`double` seems reasonable to me.

**Comment by shubhamtomar95** [comment]
The  following changes have been made : 

1. Created `src/include/common/timer.h`.

2. Moved class Timer from `src/include/execution/util/timer.h` to `src/include/common/timer.h`(namespace terrier::common).

3. Moved class `ScopedTimer` from `src/include/common/scoped_timer.h` to `src/include/common/timer.h`.

4. Removed class `ScopedTimer` of `src/include/execution/util/timer.h`.

5.Changed the invocations appropriately, methods that were invoking `ScopedTimer` class of `src/include/execution/util/timer.h` are now invoking `ScopedTimer`  of `src/include/common/timer.h`.

6. `uint_64` changed to `double`.

There are some casting issues with  `static_cast<double>(std::chrono::duration_cast<resolution>(end - start_).count());` (https://github.com/cmu-db/terrier/blob/master/src/include/common/scoped_timer.h#L34).

Before we move ahead  to resolve these, is the above  set  up as expected?

**Comment by pmenon** [comment]
Since we'll use `double`'s, use `ScopedTimer` from `src/include/execution/util/timer.h` and preserve comments from `src/include/common/scoped_timer.h`.

**Comment by shubhamtomar95** [comment]
I've made the required changes and pushed it to my forked repo, please take a look and let  me know,
In summary I've the timer logic is in `src/include/common/timer.h`.
Since there were other classes in `/src' , `/test` , `/benchmark` , `/util` that were dependent on  `src/include/common/scoped_timer.h` and `src/include/execution/util/timer.h` changes  have been made to all of them.

**Comment by shubhamtomar95** [comment]
Please take a look at the last one there are no changes in the code the just commit message(was following the conventions) .

**Comment by pmenon** [comment]
@shubhamtomar95 Create a PR so it can be reviewed. Consult the [PR process wiki page](https://github.com/cmu-db/terrier/wiki/Pull-Request-Process) for more information.

**Comment by shubhamtomar95** [comment]
Building in Debug mode (cmake -DCMAKE_BUILD_TYPE=debug -DTERRIER_USE_ASAN=ON ..)

make check-censored is throwing the following error: 
/terrier/src/include/common/timer.h:51:  static inline double TimeFunction(const F &fn) {
make[3]: *** [CMakeFiles/check-censored.dir/build.make:57: CMakeFiles/check-censored] Error 1
make[2]: *** [CMakeFiles/Makefile2:419: CMakeFiles/check-censored.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:426: CMakeFiles/check-censored.dir/rule] Error 2
make: *** [Makefile:266: check-censored] Error 2

make unittest it giving following error : 
error: ld returned 1 exit status
make[3]: *** [test/common/CMakeFiles/performance_counter_test.dir/build.make:138: debug/performance_counter_test] Error 1
make[2]: *** [CMakeFiles/Makefile2:1387: test/common/CMakeFiles/performance_counter_test.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:224: CMakeFiles/unittest.dir/rule] Error 2
make: *** [Makefile:188: unittest] Error 2

Unable to figure out how to resolve, any suggestions will be helpful and apologies for the delayed reply. I was chasing a few critical production deadlines.

**Comment by apavlo** [comment]
` /terrier/src/include/common/timer.h:51: static inline double TimeFunction(const F &fn) {`

The keyword `inline` is banned: https://github.com/cmu-db/terrier/blob/master/build-support/bad_words.txt

**Comment by apavlo** [comment]
Fixed in #653
