### ISSUE TITLE
metrics_test fails occasionally on CI

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#629]
Opening an issue to assign to myself as I take a look at it.

**Comment by crd477** [comment]
It's also been irking me for a while now that master seems to periodically fail unittest even when the corresponding PR passed.  I wonder if it's truly only `metrics_test` that's involved though.
For what it's worth, I just did a quick survey and found that `bwtree_test` and `tpcc_test` are also regular culprits:
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/388/pipeline/16
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/388/pipeline/14
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/383/pipeline/16
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/376/pipeline/16
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/376/pipeline/14

I initially wondered if they were all common to a specific worker node or type but they don't seem to be.  If there's something that comes to your mind that you'd like to investigate, I'm happy to help.  Hopefully I'm not just muddying the waters...

**Comment by mbutrovich** [comment]
Yeah `bwtree_test` and `tpcc_test` are both caused by a memory leak in the bwtree. (see #544). Trying to get it to reproduce more consistently for @wangziqi2013 to debug.

**Comment by mbutrovich** [comment]
Looped `metrics_test` for over 2 hours last night and couldn't get it to fail. I'll try fewer hardware threads in case that's the scenario that's leading to Jenkins failures.

**Comment by mbutrovich** [comment]
Have not seen this since #648 merged. The belief at the time was that it was cleaning up the races related to debug loggers and various sub-components shutting down.
