### ISSUE TITLE
Coveralls is wonky

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/terrier#63]
e.g. Although it runs bitmap_test when generating coverage files, it does not pick up the calls to Flip in bitmap.h.

Currently suspect optimizations like inlining to be the issue, though we're already running it in debug (O0, fno-inline), will need to dig more to find out.

---

This appears to be an issue with gcov (see .gcov files generated with `make coveralls_generate`). Possibly related to optimizations, inlining, and/or templating.

Tried:
- -fno-inline -fno-inline-small-functions -fno-default-inline
- -fno-elide-constructors

Can't quite get it working for now.

**Comment by lmwnshn** [comment]
Coveralls is **extremely** wonky. It went from 10% coverage to 100% coverage on bitmap.h with the #68 PR, which did not touch that file.

**Comment by mbutrovich** [comment]
We'll keep an eye out for weird numbers from Coveralls, but in general it seems reasonable lately and I don't think we should leave this open.
