### ISSUE TITLE
Enum class for trigger types in CreateStatement

### ISSUE THREAD

**Issue by mush-zhang** [cmu-db/terrier#655]
We would like to make `trigger type` in CreateStatement which corresponds to a create trigger query an enum class.

When parsing the create trigger query, trigger type information is saved in the following attributes:
`row_`, `timing_`, and `events_`, in 
https://github.com/cmu-db/terrier/blob/master/src/include/parser/parsenodes.h#L373

The above three attributes make up the `trigger type` of CreateTriggerStatement, which is processed in https://github.com/cmu-db/terrier/blob/master/src/parser/postgresparser.cpp as such

```c++
int16_t trigger_type = 0;
  TRIGGER_CLEAR_TYPE(trigger_type);
  if (root->row_) {
    TRIGGER_SETT_ROW(trigger_type);
  }
  trigger_type |= root->timing_;
  trigger_type |= root->events_;
```

The new TriggerType enum class should be created in https://github.com/cmu-db/terrier/blob/master/src/include/parser/parser_defs.h, with meaningful name of each trigger type. 

Trigger type fields in classes CreateStatement, LogicalCreateTrigger, CreateTrigger, and CreateTriggerPlanNode will need to change to this enum type as well.

**Comment by mbutrovich** [comment]
What's the "why" on this issue?

**Comment by thepinetree** [comment]
@apavlo creating an enum type would need 96 values (combinations of row_, timing_, and events_), and more lengthy checks than the bitwise method already present. The latter seems more elegant in this scenario.

**Comment by apavlo** [comment]
Why do we want to combine all the meta-data about a trigger into a single value? Why not have a separate `enum class` for the three attributes (row, timing, and events)?

**Comment by thepinetree** [comment]
Oh ok, misunderstood before.

**Comment by thepinetree** [comment]
Bad idea as we use Postgres's parser which already formats the types as they currently exist.
