### ISSUE TITLE
Expose Bw-Tree Configuration Parameters

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#666]
We want to expose some of the Bw-Tree's configuration knobs to the rest of the system so that we can try to tune them. Right now there are six knobs that are #defined, which means that we cannot change them without recompiling the system: 

https://github.com/cmu-db/terrier/blob/master/third_party/bwtree/bwtree.h#L63-L72

These #defines can stay as the default values. But then we need to add new internal data members in `BwTreeBase` with public getter/setter methods:

* `GetInnerDeltaChangeLengthThreshold` / `SetInnerDeltaChangeLengthThreshold`
* `GetLeafDeltaChangeLengthThreshold` / `SetLeafDeltaChangeLengthThreshold`
* `GetInnerSizeUpperThreshold` / `SetInnerSizeUpperThreshold` 
* `GetInnerSizeLowerThreshold` / `SetInnerSizeLowerThreshold` 
* `GetLeafSizeUpperThreshold` / `SetLeafSizeUpperThreshold` 
* `GetLeafSizeLowerThreshold` / `SetLeafSizeLowerThreshold` 

AFAIK, these parameters don't affect memory layout, therefore it is safe to dynamically change them without having to rebuild the entire tree.

We don't need to expose these knobs in the `SettingsManager` right now because we have no way of defining parameters for dynamic database objects.

**Comment by thepinetree** [comment]
Merged
