### ISSUE TITLE
Add Doxygen check to Jenkins

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#672]
Currently only Travis does the Doxygen check: https://github.com/cmu-db/terrier/blob/2d48e68108302ce8d4e9b82fcf7bb80efbaeee8c/.travis.yml#L42

We should add this to all 3 configurations in the Check stage of Jenkins. This would give us 100% CI coverage on Jenkins and allow us to eventually retire Travis.

**Comment by crd477** [comment]
How much does the group rely on the email notifications of build results from Travis?  If it's important, I can replicate that in Jenkins before Travis is actually retired.  If I remember correctly, all the necessary support is already there in the Jenkins master, it just needs to be configured or reconfigured correctly.

**Comment by mbutrovich** [comment]
I've never noticed build result emails from Travis. I would say if they do exist, they're not important. Thanks Chad!

**Comment by mbutrovich** [comment]
Fixed by #678.
