### ISSUE TITLE
PacketWriter should not have anything protocol-specific

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#685]
`PacketWriter` is the base class for `PostgresPacketWriter`. Not sure if this happened when we added ITP stuff or if it was always like that. Regardless, there's a lot of Postgres-specific stuff in `PacketWriter` which seems wrong to me. I believe that logic should be pulled to the `PostgresPacketWriter`.

I will _not_ be fixing this in my `traffic_cop` branch, but only noticed it while trying to understand how to put results back on the wire.

**Comment by tli2** [comment]
I don't remember designing PacketWriter to be an extensible class. It was a postgres-specific utility class back in the old days, not a component in the extendible framework. 

So maybe ITP shouldn't have used it?
