### ISSUE TITLE
Take log directory as parameter in TPCC benchmark

### ISSUE THREAD

**Issue by jrolli** [cmu-db/terrier#686]
The current benchmark has a hardcoded path (`benchmark/integration/tpcc_benchmark.cpp:23`) that does not exist by default and will cause a "file not found" exception when run (exists on Jenkins machine for benchmarking).  This should be taken in as a parameter with a reasonable default (i.e. `/tmp`) to allow local runs of the benchmark as well.

**Comment by apavlo** [comment]
Fixed in #701
