### ISSUE TITLE
Cleanup TAS tests

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#71]
Because TAS tests were written before the DataTable, there's duplicate logic. Although this is low priority, we should eventually clean this up and use the newer implementations. TAS test util as a class should be eventually merged into storage test util.

**Comment by tli2** [comment]
#77 merges the file. We can stand to remove FakeRawTuple still when we have time.

**Comment by yangjuns** [comment]
I have replaced FakeRawTuple by ProjectedRow in TAS tests. But TAS benchmark code also uses FakeRawTuple. I'm worried that Replacing FakeRawTuple by ProjectedRow might have some performance impact on benchmark code, which is fine for tests. Should I keep the FakeRawTuple class?
