### ISSUE TITLE
No error message when server tries to bind to port already being used

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#732]
We don't throw an error message or stop the server if it fails to listen on its target network port number. It appears that the server started up correctly from the output message even though it did not.

To reproduce, we first will start three instances of the server. All will try to bind on port 15721:
 ```
$ for x in $(seq 1 3); do ./debug/terrier & sleep 2 ; done 
[1] 17615
[2020-02-01 14:44:15.242] [network_logger] [info] Listening on port 15721
[2] 17627
[2020-02-01 14:44:17.188] [network_logger] [info] Listening on port 15721
[3] 17639
[2020-02-01 14:44:19.210] [network_logger] [info] Listening on port 15721
```
From this we can see that there are three PIDs for the terrier server. The output messages all claim that they are listening on port 15721.

But according to the OS, only the first PID is actually listening to that port:
```
$ lsof -i:15721 -t
17615
```

**Comment by mbutrovich** [comment]
Looks like `TerrierServer` throws an exception if it fails to open the port. We just don't catch it in `DBMain`. Should just be a matter of wrapping this in a `try` `catch` block to handle it.
https://github.com/cmu-db/terrier/blob/master/src/main/db_main.cpp#L13
