### ISSUE TITLE
Single Utility Class for Automatic Naming

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#750]
Right now the logic for auto-generating names for database objects (e.g., indexes, constraints) is scattered in a couple different locations:

https://github.com/cmu-db/terrier/blob/master/src/include/planner/plannodes/create_table_plan_node.h#L506
https://github.com/cmu-db/terrier/blob/master/src/include/planner/plannodes/create_table_plan_node.h#L521

We need to make a single class called `AutomaticNamingUtil` (or something better?) that has methods for generating the names of these objects. The idea is that we will have a single location where all this logical can be found. 

We should follow the naming convention of Postgres.

**Comment by wuwenw** [comment]
fixed in #761
