### ISSUE TITLE
Can I contribute to this project, if I am not a cmu student?

### ISSUE THREAD

**Issue by wgy8283335** [cmu-db/terrier#754]
Hi, I am a apache commiter. And I'm interested in the database project, but I am not a cmu student. 
So I'd like to ask whether I could be a contributor to this project?

**Comment by apavlo** [comment]
Yes, we take PRs from anybody! Start with a beginner task:

https://github.com/cmu-db/terrier/issues?q=is%3Aissue+is%3Aopen+label%3Abeginner

**Comment by wgy8283335** [comment]
That's great!!!  I've learned your 15-445, and just start to learn 15-721. Thank you very much for your lesson and your self-driving database project.
