### ISSUE TITLE
Alias Renaming (AS) Does Not Work for Output Columns

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#779]
The DBMS currently ignores aliased column names in the output list. 
```
terrier=# CREATE TABLE xxx (id INT);
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1),(2),(3),(4);
INSERT 0 4
terrier=# SELECT id AS new_name FROM xxx;
 id 
----
  1
  2
  3
  4
(4 rows)
```

It also does not work if you give a constant as the output:
```
terrier=# SELECT 1 AS new_name FROM xxx;
 INTEGER 
---------
       1
       1
       1
       1
(4 rows)
```

**Comment by apavlo** [comment]
We also need this for TPC-C StockLevel:

```
SELECT COUNT(DISTINCT S_I_ID) AS STOCK_COUNT
  FROM ORDER LINE, STOCK
 WHERE OL_W_ID = 1
   AND OL_D_ID = 2
   AND OL_O_ID < 3
   AND OL_O_ID >= 4
   AND S_W_ID = 5
   AND S_I_ID = OL_I_ID
   AND S_QUANTITY < 6
```

**Comment by apavlo** [comment]
@wuwenw Other queries to test. Write test cases for these:

1. `SELECT a AS b, b AS a FROM xxx;`
2. `SELECT COUNT(*) AS cnt FROM xxx HAVING cnt > 10;`
3. `SELECT a AS a, b AS b FROM xxx;`
4. `SELECT a, b AS a FROM xxx;` <--- This should fail

**Comment by wuwenw** [comment]
> 2\. SELECT COUNT(*) AS cnt FROM xxx HAVING cnt > 10;
This query doesn't work in terrier nor in postgres. Is it a typo? 

SELECT COUNT(*) AS cnt FROM xxx HAVING COUNT(*) > 10; works in postgres but it seems we have some issue with HAVING, as mentioned in #793.

> 4\. SELECT a, b AS a FROM xxx; <--- This should fail, but it works in postgres.
