### ISSUE TITLE
Retain CTest Output Files

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#822]
After we run `make unittest` in our Jenkins pipeline, we need to save the output files so that we can go back and see why things are failing. Right now I think we are just blowing all the files away.

**Comment by crd477** [comment]
I have a diff that I'm testing now that fixes this.  If you'd like to take a look at the output, see:
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/crd%2Fterrier-crd/detail/terrier-822/9/tests

Note that the layout is significantly different if you're using the Blue Ocean interface versus the traditional Jenkins interface:
http://jenkins.db.cs.cmu.edu:8080/job/crd/job/terrier-crd/job/terrier-822/9/testReport/

I actually prefer the organization in the latter but it's just a different view.
Let me know if this does what you want and I'll submit a PR.

**Comment by crd477** [comment]
Here are the results from a completed pipeline:
http://jenkins.db.cs.cmu.edu:8080/job/crd/job/terrier-crd/job/terrier-822/15/testReport/

The results in "(root)" are from the microbenchmark junit tests and the results in "projectroot.test" are the results from the CTest unit tests.

If this looks good, I'll submit the PR.

**Comment by apavlo** [comment]
@crd477 It looks like it cut it off after 1KB:

http://jenkins.db.cs.cmu.edu:8080/job/crd/job/terrier-crd/job/terrier-822/15/testReport/projectroot.test/settings/Test___ubuntu_18_04_clang_8_0_0__Release_unittest____settings_test/

Also, this looks like it only capture stdout. Is it possible to also get stderr?

**Comment by crd477** [comment]
OK, I worked around the 1KB limit.  Please have a look here:
http://jenkins.db.cs.cmu.edu:8080/job/crd/job/terrier-crd/job/terrier-822/19/testReport/projectroot.test/

I did not see any explicit way to capture stderr but I'll keep looking.  I'm not sure what circumstances these gtest-based tests will write there.

**Comment by apavlo** [comment]
@crd477 Any update?

**Comment by crd477** [comment]
Sorry, I was just reminded about this by @lmwnshn's mention of unittest failures in #928.  I'll resolve it ASAP.

**Comment by crd477** [comment]
> Also, this looks like it only capture stdout. Is it possible to also get stderr?

I modified one of the unit tests as follows:
```
TEST(TypeUtilTests, ShouldFailTest) {
  // write to stderr to test ctest logging
  std::cerr << "TEST SPEWAGE TO STDERR" << std::endl;
  EXPECT_EQ(2 + 2, 5);
}
```
I didn't see that text appear in the individual logfile (`build/test-logs/type_util_test.txt`) but this is what wound up in the the aggregated XML file:
```
...
                                        <Value>Running type_util_test, redirecting output into /terr
ier/build/build/test-logs/type_util_test.txt (attempt 1/1)
Running main() from gmock_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from TypeUtilTests
[ RUN      ] TypeUtilTests.GetTypeSizeTest
[       OK ] TypeUtilTests.GetTypeSizeTest (0 ms)
[ RUN      ] TypeUtilTests.TypeIdToStringTest
[       OK ] TypeUtilTests.TypeIdToStringTest (0 ms)
[ RUN      ] TypeUtilTests.ShouldFailTest
TEST SPEWAGE TO STDERR
/terrier/test/type/type_util_test.cpp:47: Failure
      Expected: 2 + 2
      Which is: 4
To be equal to: 5
[  FAILED  ] TypeUtilTests.ShouldFailTest (0 ms)
[----------] 3 tests from TypeUtilTests (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TypeUtilTests.ShouldFailTest

 1 FAILED TEST
/terrier/build/test/type
</Value>
...
```
That should be sufficient to see it in the output from the Jenkins pipeline so at least it's an improvement over the current situation.

If you're OK with this, let me know and I'll submit the PR momentarily.
