### ISSUE TITLE
Rewrite SpinLatch wait

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#83]
@mbutrovich is suggesting that _mm_pause() will perform terribly on newer platforms.

We can probably replace that with newer language features.

**Comment by mbutrovich** [comment]
The discussion stemmed from Intel’s own docs saying that the PAUSE instruction’s latency is an order of magnitude longer on Skylake and newer:

https://software.intel.com/en-us/articles/a-common-construct-to-avoid-the-contention-of-threads-architecture-agnostic-spin-wait-loops

That said, we’re only using the Spinlatch in one place and it’s not a performance issue until it’s measured.
