### ISSUE TITLE
Tests for ProjectedRow, DeltaRecord, and StorageUtils

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#85]
We kind of didn't care much about them because they are relatively simple and tested in data table anyway.

However, I've been making changes to their structures and realized that the change is split in several places and easy to miss. Maybe we should have a small test suite for them, just like MemorySafety test for TupleAccessStrategy, to make mistakes easier to spot down the line.

**Comment by mbutrovich** [comment]
Resolved by #103.
