### ISSUE TITLE
Python Test Harness: Cannot Start DBMS in Debug Mode

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#865]
The reason why our junit tests have been failing recently is because for some reason the DBMS does not start when compiled in debug mode. I have no reason why this happens. This issue occurs for both the junit and oltp-bench tests.

For now I have disabled running the Python testing harness in debug mode. We only run it if the DBMS is compiled in release mode.

We need to investigate why this is happening and re-enable Python testing for debug mode.

**Comment by crd477** [comment]
(@apavlo and I have been going back and forth in email about this but it seems more appropriate to discuss it here.)

New theory: the docker builders are currently configured with too many executor slots and the host sometimes runs out of memory.  It doesn't help that Jenkins apparently likes to cram all of the stages on a single host when it can.
I watched while this pipeline was running: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/crd%2Fterrier-crd/detail/terrier-822/11/pipeline
and indeed, the memory was always nearly full.  Another strong hint was this failure:
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/crd%2Fterrier-crd/detail/terrier-822/8/tests

I'm going to halve the number of executors on the docker hosts and see if this helps.

**Comment by apavlo** [comment]
I don't think this is an issue anymore. We can run it in debug mode. The failure to bind to the right port is due to another problem.
