### ISSUE TITLE
psql version

### ISSUE THREAD

**Issue by DreaMer963** [cmu-db/terrier#902]
「Peloton has been tested to work with psql version 9.5.4.」
So terrier ?

My pg version is 12.3. When I connected to terrier, I got the following error.

```
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

```

**Comment by mbutrovich** [comment]
```
matt@Matts-MBP ~ % psql --version
psql (PostgreSQL) 12.3
matt@Matts-MBP ~ % psql -h localhost -p 15721 -d terrier
psql (12.3, server 9.5devel)
Type "help" for help.

terrier=# 
```
12.3 works okay here. Can you describe a bit more about your setup (OS, compiler, etc.) and the psql command that you're using?

**Comment by DreaMer963** [comment]
*OS**
```
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,4
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 1.7 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      Boot ROM Version: 1037.80.53.0.0 (iBridge: 17.16.13050.0.0,0)
```
**compiler**
```
llvm@8
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
```

my operator is following:
after terrier is running:
[2020-05-16 20:45:30.651] [network_logger] [info] Listening on port 15721
I used this psql command: **psql -h localhost -p 15721 -d terrier**   and got  an error.

but if I connect the default port 5432, it's ok
```
psql -h localhost -p 5432 -d terrier                                                                                                                                                  
psql (12.3)
Type "help" for help.

terrier=# 
```

**Comment by mbutrovich** [comment]
How are you starting the terrier server?

**Comment by DreaMer963** [comment]
```
mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j4
```
then found a terrier binary under the release folder: **./terrier**


but this time I found a strange warning when I executed **make -j4**
```
ld: warning: directory not found for option '-L/usr/local/opt/postgresql@9.5/lib'
```
however, I only have **/usr/local/opt/postgresql@12/lib**

**Comment by DreaMer963** [comment]
psql connected the terrier successfully on my ubuntu system.
Thanks for your reply!
