### ISSUE TITLE
Convert the nightly build into a Jenkinsfile

### ISSUE THREAD

**Issue by skyfishjy** [cmu-db/terrier#937]
The nightly build is currently just a script written on Jenkins. The MSE Team wants to convert it into a file stored in the repo so that we could have `Stage Step` in our nightly build that runs OLTPbench and other jobs in the future.

The way to do that is to add another `Jenkinsfile` (with a different name, maybe `Jenkinsfile-nightly`?) And configure the [terrier-nightly pipeline](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier-nightly/activity). In the `Jenkins Configure - Build Configuration`, we change the Script Path:

![Screenshot from 2020-06-03 00-46-49](https://user-images.githubusercontent.com/996019/83596873-c37ebe80-a533-11ea-9bb7-9735bbf263cf.png)
 
The MSE Team is working on the nightly Jenkinsfile. We need @crd477 and @apavlo 's review after we finish it and update the Jenkins Pipeline configuration so that we could test it.

Feel free to discuss this.

**Comment by crd477** [comment]
(related to #840)
