### ISSUE TITLE
Connection to the db fails

### ISSUE THREAD

**Issue by yvxiang** [cmu-db/terrier#978]
The server has already started:
➜  debug git:✗ ./terrier
[2020-06-20 22:34:23.598] [network_logger] [info] Listening on port 15721

But when try to connect to the server, fails get:
➜  bin  psql --host=localhost --port=15721
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

Any suggestion about how to figure out what's the problem?

**Comment by mbutrovich** [comment]
You have to specify `-d terrier` to connect to the default database.

**Comment by yvxiang** [comment]
➜  bin git:(master) ✗ psql --host=localhost --port=15721 -d terrier
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

The same result. Something to initialize?

**Comment by yvxiang** [comment]
> You have to specify `-d terrier` to connect to the default database.

➜ bin git:(master) ✗ psql --host=localhost --port=15721 -d terrier
psql: error: could not connect to server: server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.

The same result. Something to initialize?

**Comment by mbutrovich** [comment]
Without seeing a Wireshark trace I couldn't say for sure.

**Comment by yvxiang** [comment]
![image](https://user-images.githubusercontent.com/1382038/85219805-53988100-b3d9-11ea-93fa-9610dd9f58bf.png)

Seems refused after send 8 bytes: 00 00 00 08 04 d2 16 30

**Comment by apavlo** [comment]
Unable to reproduce locally.
